const fs = require('fs');
const path = require('path');

const filepath = path.join(__dirname, 'src', 'core', 'secret-formula', 'achievements', 'normal-achievements.js');

let content = fs.readFileSync(filepath, 'utf-8');

const T = [
  // === REWARD STRINGS ===
  // Ach 12
  ['`Multiply the 2nd Antimatter Dimension by the Antimatter Exponent.`', '`以反物质指数乘第二反物质维度。`'],
  // Ach 13
  ['`The 3rd and higher Antimatter Dimensions are ${formatPercents(0.3)} stronger.`', '`第三及更高反物质维度强度提升${formatPercents(0.3)}。`'],
  // Ach 14
  ['`The 4th Antimatter Dimension is multiplied by ${formatInt(4)}.`', '`第四反物质维度乘以${formatInt(4)}。`'],
  // Ach 15
  ['`The 5th and higher Antimatter Dimensions are doubled.`', '`第五及更高反物质维度翻倍。`'],
  // Ach 16
  ['`Multiply the 6th Antimatter Dimension by ${formatInt(9)}.`', '`以${formatInt(9)}乘第六反物质维度。`'],
  // Ach 17
  ['`Multiply the 7th Antimatter Dimension by ${formatInt(7)}.`', '`以${formatInt(7)}乘第七反物质维度。`'],
  // Ach 18
  ['`Multiply all Antimatter Dimensions by Ninety Degrees.`', '`以九十度乘所有反物质维度。`'],
  // Ach 21
  ['`Start with ${formatInt(100)} antimatter.`', '`以${formatInt(100)}反物质起始。`'],
  // Ach 23
  ['`8th Antimatter Dimensions are ${formatPercents(0.1)} stronger.`', '`第八反物质维度强度提升${formatPercents(0.1)}。`'],
  // Ach 28
  ['`1st Antimatter Dimensions are ${formatPercents(0.1)} stronger.`', '`第一反物质维度强度提升${formatPercents(0.1)}。`'],
  // Ach 31
  ['`1st Antimatter Dimensions are ${formatPercents(0.05)} stronger.`', '`第一反物质维度强度提升${formatPercents(0.05)}。`'],
  // Ach 32
  ['`Dimensional Sacrifice is stronger.', '`维度献祭强度提升。'],
  ['      ${Sacrifice.getSacrificeDescription({ "Achievement32": false, "Achievement57": false, "Achievement88": false })} ➜', '      ${Sacrifice.getSacrificeDescription({ "Achievement32": false, "Achievement57": false, "Achievement88": false })} ➜'],
  ['      ${Sacrifice.getSacrificeDescription({ "Achievement32": true, "Achievement57": false, "Achievement88": false })}`', '      ${Sacrifice.getSacrificeDescription({ "Achievement32": true, "Achievement57": false, "Achievement88": false })}`'],
  
  // More rewards...
  ['`All Antimatter Dimensions are ${formatPercents(0.1)} stronger.`', '`所有反物质维度强度提升${formatPercents(0.1)}。`'],
  ['`All Antimatter Dimensions are ${formatPercents(0.4)} stronger, but only in challenges.`', '`所有反物质维度强度提升${formatPercents(0.4)}，但仅限挑战中。`'],
  ['`All Antimatter Dimensions are raised to ${formatPow(1.1012920825630384, 0, 3)}`', '`所有反物质维度提升至${formatPow(1.1012920825630384, 0, 3)}`'],
  ['`All Dimensions are ${formatPercents(0.1)} stronger.`', '`所有维度强度提升${formatPercents(0.1)}。`'],
  ['`All Galaxies are ${formatPercents(0.01)} stronger.`', '`所有星系强度提升${formatPercents(0.01)}。`'],
  ['`All Infinity Dimension multipliers are doubled.`', '`所有无限维度倍率翻倍。`'],
  ['`All Infinity Dimensions are stronger based on Infinity Points.`', '`所有无限维度基于无量点获得强化。`'],
  ['`Antimatter Dimensions 1-4 are ${formatPercents(0.25)} stronger.`', '`反物质维度一至四强度提升${formatPercents(0.25)}。`'],
  ['`Black Hole durations are ${formatPercents(0.1)} longer.`', '`黑洞持续时间延长${formatPercents(0.1)}。`'],
  ['`Black Hole intervals are ${formatPercents(0.1)} shorter.`', '`黑洞间隔缩短${formatPercents(0.1)}。`'],
  ['`Black Hole power increased by ${formatPercents(0.1)}.`', '`黑洞强度提升${formatPercents(0.1)}。`'],
  ['`Boost Celestial Point Gain.`', '`提升天体点获取。`'],
  ['`Decrease Galaxy Generator Instability by ${formatInt(2)}.`', '`星系生成不稳定性降低${formatInt(2)}。`'],
  ['`Dimension Boosts are ${formatPercents(0.5)} stronger.`', '`维度跃升强度提升${formatPercents(0.5)}。`'],
  ['`Dimensional Sacrifice doesn\'t reset your Antimatter Dimensions`', '`维度献祭不再重置反物质维度`'],
  ['`and the Autobuyer activates every tick if turned on.`', '`且自动购买启用后每tick均激活。`'],
  ['`Dimensional Sacrifice is stronger.`', '`维度献祭强度提升。`'],
  ['`Dimensions 1-7 are ${formatPercents(0.02)} stronger.`', '`维度一至七强度提升${formatPercents(0.02)}。`'],
  ['`Each Antimatter Dimension gains a boost proportional to tier`', '`每个反物质维度获得与其等级成正比的加成`'],
  ['`(8th gets ${formatPercents(0.08)}, 7th gets ${formatPercents(0.07)}, etc.)`', '`(第八得${formatPercents(0.08)}，第七得${formatPercents(0.07)}，以此类推)`'],
  ['`Galaxies are ${formatPercents(0.1)} stronger.`', '`星系强度提升${formatPercents(0.1)}。`'],
  ['`Gain ${formatX(2)} Dilated Time and Time Theorems while Dilated.`', '`延时间时获得${formatX(2)}倍延时间与时间定理。`'],
  ['`Gain ${formatX(2)} more Eternities.`', '`获得${formatX(2)}倍更多永恒。`'],
  ['`Gain ${formatX(3)} more Eternities.`', '`获得${formatX(3)}倍更多永恒。`'],
  ['`Gain a small multiplier to Ethereal Power based on Imaginary Machines.`', '`基于虚构机器获得以太之力的小型倍率。`'],
  ['`Gain a small multiplier to the Celestial Matter Conversion Exponent based on unnerfed Celestial Matter.`', '`基于未削弱天体物质获得天体物质转化指数的小型倍率。`'],
  ['`Gain a small power to Eternity Points based on Penteracts.`', '`基于五维超立方获得永点的小型倍率。`'],
  ['`Gain ×${formatInt(1024)} more Infinities.`', '`获得×${formatInt(1024)}倍更多无限。`'],
  ['`Get ${formatPercents(0.1)} more memories.`', '`获得${formatPercents(0.1)}更多记忆。`'],
  ['`Get all Antimatter Dimension multipliers over ${formatX(DC.NUMMAX, 1)}.`', '`使所有反物质维度倍率超过${formatX(DC.NUMMAX, 1)}。`'],
  ['`Get more than ${format(DC.E29)} ticks per second.`', '`每秒tick超过${format(DC.E29)}。`'],
  ['`Get more than ${format(DC.E58)} ticks per second.`', '`每秒tick超过${format(DC.E58)}。`'],
  ['`Glyph sacrifice is ${formatX(2)} stronger.`', '`符文献祭强度提升${formatX(2)}倍。`'],
  ['`Increase the multiplier for buying ${formatInt(10)} Antimatter Dimensions by +${formatPercents(0.01)}.`', '`购买${formatInt(10)}反物质维度的倍率+${formatPercents(0.01)}。`'],
  ['`Infinities more than ${formatInt(5)} seconds long`', '`持续超过${formatInt(5)}秒的无限`'],
  ['`give ${formatX(250)} more Infinities.`', '`获得${formatX(250)}更多无限。`'],
  ['`Momentum increases ${formatX(10)} faster.`', '`动量提升速度加快${formatX(10)}倍。`'],
  ['`Multiply starting tick speed by ${format(1.02, 2, 2)}.`', '`起始tick速度乘以${format(1.02, 2, 2)}。`'],
  ['`Multiply starting tickspeed by ${formatX(1.02, 0, 2)}.`', '`起始tick速度乘以${formatX(1.02, 0, 2)}。`'],
  ['`Reach ${formatX(1000)} faster per Tickspeed upgrade.`', '`每次tick速度升级加快${formatX(1000)}。`'],
  ['`Replicanti Galaxies divide your Replicanti by ${format(DC.NUMMAX, 1, 0)}`', '`复制元星系以${format(DC.NUMMAX, 1, 0)}除你的复制元`'],
  ['`instead of resetting them to ${formatInt(1)}.`', '`而非将其重置为${formatInt(1)}。`'],
  ['`Start Eternities with ${format(5e25)} Infinity Points.`', '`永恒起始时获得${format(5e25)}无量点。`'],
  ['`Synergism can go above ${formatPercents(1)} and Momentum increases ${formatX(10)} faster.`', '`协同可超过${formatPercents(1)}，动量提升速度加快${formatX(10)}倍。`'],
  ['`The multiplier from Dimension Boosts to Antimatter Dimensions is ${formatPercents(0.01)} higher.`', '`维度跃升对反物质维度的倍率提升${formatPercents(0.01)}。`'],
  ['`Tickspeed is just over ${formatPercents(0.05)} faster per Antimatter Galaxy.`', '`每个反物质星系使tick速度提升略超${formatPercents(0.05)}。`'],
  ['`Unlock two new Infinity Upgrades- ${formatX(2)} IP multiplier and offline IP generation.`', '`解锁两个新无限升级——${formatX(2)}无量点倍率与离线无量点生成。`'],
  ['`You gain ${formatX(2)} times more Infinities and`', '`获得${formatX(2)}倍更多无限，且`'],
  ['`after Eternity you permanently keep ${formatPercents(0.05)} of your Infinities as Banked Infinities.`', '`永恒后永久保留${formatPercents(0.05)}的无限为储存无限。`'],
  ['`You gain Replicanti ${formatInt(2)} times faster under ${format(replicantiCap(), 1)} Replicanti.`', '`在${format(replicantiCap(), 1)}复制元以下，复制元获取速度${formatInt(2)}倍。`'],
  ['`You gain Replicanti ${formatInt(3)} times faster.`', '`复制元获取速度${formatInt(3)}倍。`'],
  ['`You keep your Replicanti and ${formatInt(1)} Replicanti Galaxy on Infinity.`', '`无限时保留复制元及${formatInt(1)}复制元星系。`'],
  ['`+${formatInt(69)} to Glyph level.`', '`符文等级+${formatInt(69)}。`'],
  ['`+${formatInt(value)}`', '`+${formatInt(value)}`'],
  ['`+${formatPercents(0.01)} Glyph rarity.`', '`符文稀有度+${formatPercents(0.01)}。`'],
  ['`Additional ${formatX(4)} multiplier to Infinity Points.`', '`无量点额外${formatX(4)}倍率。`'],
  ['`Alpha Decay increases ${formatX(1.1, 1, 1)} faster`', '`阿尔法衰变速率提升${formatX(1.1, 1, 1)}倍`'],
  ['`Alpha Decay speed is boosted based on Dual Machines.`', '`阿尔法衰变速度基于双机器提升。`'],
  ['`Dilate Antimatter Dimension Multipliers based on purchased Endgame Skills, which is stronger in Pelle.`', '`基于已购终局技能扩展反物质维度倍率，在佩勒中效果更强。`'],
  ['`Double the Celestial Matter Conversion Exponent.`', '`天体物质转化指数翻倍。`'],
  ['`Each Antimatter Dimension gains a boost proportional to tier`', '`每个反物质维度获得与其等级成正比的加成`'],
  ['`Get a small multiplier to the Celestial Matter Conversion Exponent based on unnerfed Celestial Matter.`', '`基于未削弱天体物质获得天体物质转化指数的小型倍率。`'],
  ['`Get ${format(DC.E9, 3)} Banked Infinities.`', '`获得${format(DC.E9, 3)}储存无限。`'],
  ['`Get ${format(DC.NUMMAX, 1)} Infinities.`', '`获得${format(DC.NUMMAX, 1)}无限。`'],
  ['`Get ${formatInt(1000)} Free Tesseracts.`', '`获得${formatInt(1000)}免费超立方体。`'],
  ['`Get ${formatX(500)} more memories.`', '`获得${formatX(500)}更多记忆。`'],
  ['`Get a ${formatX(DC.NUMMAX, 1, 0)} multiplier in a single Dimensional Sacrifice.`', '`单次维度献祭获得${formatX(DC.NUMMAX, 1, 0)}倍率。`'],
  ['`Get a Glyph with ${formatInt(4)} effects.`', '`获得具有${formatInt(4)}种效果的符文。`'],
  ['`Get a Glyph with level ending in ${formatInt(6969)}.`', '`获得等级尾数为${formatInt(6969)}的符文。`'],
  ['`Get a level ${formatInt(5000)} Glyph with all Glyph level factors equally weighted.`', '`获得等级${formatInt(5000)}的符文，所有等级因子均等加权。`'],
  ['`Get a total Dimensional Sacrifice multiplier of ${formatPostBreak(DC.E9000)}.`', '`维度献祭总倍率达到${formatPostBreak(DC.E9000)}。`'],
  ['`Get all Antimatter Dimension multipliers over ${formatX(DC.E31)}.`', '`使所有反物质维度倍率超过${formatX(DC.E31)}。`'],
  ['`Get all of your Antimatter Dimension Autobuyer bulk amounts to`', '`使所有反物质维度自动购买批量达到`'],
  ['`${formatInt(Autobuyer.antimatterDimension.bulkCap)}.`', '`${formatInt(Autobuyer.antimatterDimension.bulkCap)}。`'],
  ['`Get more than ${formatPostBreak("1e8296262")} ticks per second.`', '`每秒tick超过${formatPostBreak("1e8296262")}。`'],
  ['`Get more than ${formatPostBreak("ee29")} ticks per second.`', '`每秒tick超过${formatPostBreak("ee29")}。`'],
  ['`Get the sum of Infinity Challenge times below ${formatInt(750)}ms.`', '`无限挑战时间总和低于${formatInt(750)}ms。`'],
  ['`Get the sum of Infinity Challenge times under ${format(6.66, 2, 2)} seconds.`', '`无限挑战时间总和低于${format(6.66, 2, 2)}秒。`'],
  ['`Get the sum of all best Normal Challenge times under ${formatInt(5)} seconds.`', '`所有常规挑战最佳时间总和低于${formatInt(5)}秒。`'],
  ['`Get the sum of all of your Normal Challenge times under ${formatInt(3)} minutes.`', '`所有常规挑战时间总和低于${formatInt(3)}分钟。`'],
  ['`Hadronize Lai\'tela\'s Reality ${formatInt(50)} times.`', '`对莱特拉真境进行${formatInt(50)}次强子化。`'],
  ['`Have ${formatInt(100)} Glyphs in your inventory.`', '`背包中拥有${formatInt(100)}个符文。`'],
  ['`Have ${formatInt(180)} times more Replicanti Galaxies than Antimatter Galaxies.`', '`复制元星系数量为反物质星系的${formatInt(180)}倍。`'],
  ['`Have ${formatInt(308)} Tickspeed upgrades from Time Dimensions.`', '`从时间维度获得${formatInt(308)}次tick速度升级。`'],
  ['`Have ${formatInt(569)} Antimatter Galaxies without gaining any`', '`拥有${formatInt(569)}反物质星系，且未获得任何`'],
  ['`Replicanti Galaxies in your current Eternity.`', '`当前永恒中的复制元星系。`'],
  ['`Have a game speed of ${format(DC.NUMMAX, 1)} with Celestial Matter toggled off.`', '`关闭天体物质时游戏速度达到${format(DC.NUMMAX, 1)}。`'],
  ['`Have all your Eternities in your past ${formatInt(10)} Eternities be at least`', '`过去${formatInt(10)}次永恒中，每次永恒的永点至少为前一次的`'],
  ['`${format(DC.NUMMAX, 1, 0)} times higher Eternity Points than the previous one.`', '`${format(DC.NUMMAX, 1, 0)}倍。`'],
  ['`Have all your Infinities in your past ${formatInt(10)} Infinities be at least`', '`过去${formatInt(10)}次无限中，每次无限的无量点至少为前一次的`'],
  ['`${format(DC.NUMMAX, 1, 0)} times higher Infinity Points than the previous one.`', '`${format(DC.NUMMAX, 1, 0)}倍。`'],
  ['`Have antimatter per second exceed your current antimatter`', '`每秒反物质产生超过当前反物质`'],
  ['`for ${formatInt(30)} consecutive seconds.`', '`持续${formatInt(30)}秒。`'],
  ['`Have antimatter per second exceed your current antimatter above ${format(DC.E63)}.`', '`每秒反物质产生超过当前反物质，突破${format(DC.E63)}。`'],
  ['`Have your Infinity Dimension purchase cap exceed ${format(DC.NUMMAX, 1, 0)}.`', '`无限维度购买上限超过${format(DC.NUMMAX, 1, 0)}。`'],
  ['`Have your Infinity Power per second exceed your Infinity Power`', '`每秒无限之力产生超过当前无限之力`'],
  ['`for ${formatInt(60)} consecutive seconds during a single Infinity.`', '`单次无限中持续${formatInt(60)}秒。`'],
  ['`Increase the multiplier per repeatable Dilated Time`', '`每个可重复延时间的倍率提升`'],
  ['`multiplier upgrade by ${formatX(1.35, 0, 2)}.`', '`升级${formatX(1.35, 0, 2)}。`'],
  ['`Infinity ${format(DC.D2E6)} times.`', '`无限${format(DC.D2E6)}次。`'],
  ['`Infinity Upgrades stay charged on Endgame.`', '`终局时无限升级保持充能。`'],
  ['`Make the Infinity Point formula better. log(x)/${formatInt(308)} ➜ log(x)/${formatFloat(307.8, 1)}`', '`优化无量点公式。log(x)/${formatInt(308)} ➜ log(x)/${formatFloat(307.8, 1)}`'],
  ['`Own a Reality Glyph of level ${formatInt(25001)} or higher.`', '`拥有等级${formatInt(25001)}或更高的真境符文。`'],
  ['`Play for ${formatFloat(13.7, 1)} billion years.`', '`游玩${formatFloat(13.7, 1)}十亿年。`'],
  ['`Purchase ${formatInt(1000)} Endgame Skills.`', '`购入${formatInt(1000)}个终局技能。`'],
  ['`Purchase Time Study 181 while Doomed.`', '`毁灭时购入时间研究181。`'],
  ['`Raise the Antimatter Exponent to the power of ${format(1.4, 2, 1)}, but only inside Pelle.`', '`将反物质指数提升至${format(1.4, 2, 1)}，但仅限佩勒内。`'],
  ['`Reduce the Celestial Matter softcap magnitude by ${formatPercents(0.05)}.`', '`天体物质软上限幅度降低${formatPercents(0.05)}。`'],
  ['`The time for Hadron effects to cap is halved.`', '`强子效应达到上限的时间减半。`'],
  ['`Unlock Celestial Dimension Expansion.`', '`解锁天体维度扩展。`'],
  ['`Unlock Divinity.`', '`解锁神性。`'],
  ['`Unlock Effarig\'s second shop.`', '`解锁埃法里格第二商店。`'],
  ['`Unlock Strike Disabling.`', '`解锁打击禁用。`'],
  ['`You can equip up to ${formatInt(2)} Effarig and Reality Glyphs each.`', '`最多可装备${formatInt(2)}个埃法里格与真境符文。`'],
  ['`${formatPercents(EndgameMastery(41).isBought ? 1 : 0.1)} chance each Reality of ${formatX(2)}`', '`每次真境有${formatPercents(EndgameMastery(41).isBought ? 1 : 0.1)}几率获得${formatX(2)}`'],
  ['`Realities and Perk Points.`', '`真境与天赋点。`'],
  ['`${formatX(4)} Infinity Point gain, and increase the multiplier for buying ${formatInt(10)}`', '`${formatX(4)}倍无量点获取，提升购买${formatInt(10)}的倍率`'],
  ['`Antimatter Dimensions by +${format(0.1, 0, 1)}.`', '`反物质维度+${format(0.1, 0, 1)}。`'],
  ['`${formatX(value)}`', '`${formatX(value)}`'],
  ['`${formatX(value, 2, 2)}`', '`${formatX(value, 2, 2)}`'],
  ['`${formatX(value, 2, 3)}`', '`${formatX(value, 2, 3)}`'],
  ['`${formatX(value, 3)}`', '`${formatX(value, 3)}`'],
  ['`${formatX(value.pow(1 / TimeStudy(31).effectValue), 2, 1)} (After TS31: ${mult})`', '`${formatX(value.pow(1 / TimeStudy(31).effectValue), 2, 1)} (时间研究31后: ${mult})`'],
  ['`${formatX(value.recip(), 2, 2)}`', '`${formatX(value.recip(), 2, 2)}`'],
  
  // === DESCRIPTION STRINGS ===
  ['`Encounter ${formatInt(50)} different news messages.`', '`邂逅${formatInt(50)}种不同的新闻消息。`'],
  ['`Have exactly ${formatInt(99)} 8th Antimatter Dimensions.`', '`恰好拥有${formatInt(99)}个第八反物质维度。`'],
  ['`Get over ${format(DC.E80)} antimatter.`', '`获得超过${format(DC.E80)}反物质。`'],
  ['`Buy ${formatInt(10)} Dimension Boosts.`', '`购买${formatInt(10)}个维度跃升。`'],
  ['`Buy ${formatInt(2)} Antimatter Galaxies.`', '`购买${formatInt(2)}个反物质星系。`'],
  ['`Buy a single 1st Antimatter Dimension when you have over ${format(DC.E150)} of them.`', '`当拥有超过${format(DC.E150)}个第一反物质维度时，再购买一个。`'],
  ['`Buy an Antimatter Galaxy without Dimensional Sacrificing.`', '`不进行维度献祭而购买反物质星系。`'],
  ['`(Your Antimatter Galaxies are reset on Infinity.)`', '`(反物质星系在无限时重置。)`'],
  ['`Complete ${formatInt(3)} Normal Challenges.`', '`完成${formatInt(3)}个常规挑战。`'],
  ['`Complete ${formatInt(50)} unique Eternity Challenge tiers.`', '`完成${formatInt(50)}个独特永恒挑战等级。`'],
  ['`Complete all ${formatInt(12)} Normal Challenges.`', '`完成所有${formatInt(12)}个常规挑战。`'],
  ['`Complete all ${formatInt(8)} Infinity Challenges.`', '`完成所有${formatInt(8)}个无限挑战。`'],
  ['`Complete all the Eternity Challenges ${formatInt(5)} times with less than ${formatInt(1)}`', '`完成所有永恒挑战${formatInt(5)}次，每次用时少于${formatInt(1)}`'],
  ['`second (game time) in your current Reality.`', '`秒(游戏时间)，在当前真境中。`'],
  ['`Complete the 2nd Antimatter Dimension Autobuyer Challenge in ${formatInt(3)} minutes or less.`', '`在${formatInt(3)}分钟或更短时间内完成第二反物质维度自动购买挑战。`'],
  ['`Complete the 3rd Antimatter Dimension Autobuyer Challenge in ${formatInt(10)} seconds or less.`', '`在${formatInt(10)}秒或更短时间内完成第三反物质维度自动购买挑战。`'],
  ['`Complete the 8th Antimatter Dimension Autobuyer Challenge in ${formatInt(3)} minutes or less.`', '`在${formatInt(3)}分钟或更短时间内完成第八反物质维度自动购买挑战。`'],
  ['`Complete the Tickspeed Autobuyer Challenge in ${formatInt(3)} minutes or less.`', '`在${formatInt(3)}分钟或更短时间内完成tick速度自动购买挑战。`'],
  ['`Defeat Alpha.`', '`击败阿尔法。`'],
  ['`Dilate Antimatter Dimension Multipliers based on purchased Endgame Skills, which is stronger in Pelle.`', '`基于已购终局技能扩展反物质维度倍率，在佩勒中效果更强。`'],
  ['`Double the Celestial Matter Conversion Exponent.`', '`天体物质转化指数翻倍。`'],
  ['`Eternity in under ${formatInt(250)}ms.`', '`${formatInt(250)}ms内完成永恒。`'],
  ['`Eternity in under ${formatInt(30)} seconds.`', '`${formatInt(30)}秒内完成永恒。`'],
  ['`Eternity with exactly ${formatInt(9)} Replicanti.`', '`恰好拥有${formatInt(9)}复制元时进行永恒。`'],
  ['`Eternity with less than ${formatInt(10)} Infinities.`', '`无限数少于${formatInt(10)}时进行永恒。`'],
  ['`Eternity with only ${formatInt(1)} Infinity.`', '`仅拥有${formatInt(1)}无限时进行永恒。`'],
  ['`Enter Alpha\'s Reality.`', '`进入阿尔法真境。`'],
  ['`Gain ${format(DC.NUMMAX, 1, 0)} Replicanti in ${formatInt(1)} hour.`', '`在${formatInt(1)}小时内获得${format(DC.NUMMAX, 1, 0)}复制元。`'],
  ['`Get ${formatInt(10)} Replicanti Galaxies in ${formatInt(15)} seconds.`', '`在${formatInt(15)}秒内获得${formatInt(10)}个复制元星系。`'],
  ['`Get ${formatInt(100000)} Antimatter Galaxies.`', '`获得${formatInt(100000)}个反物质星系。`'],
  ['`Get ${formatInt(25000)} of all Alchemy Resources.`', '`获得${formatInt(25000)}所有炼金资源。`'],
  ['`Get ${formatInt(50)} Antimatter Galaxies.`', '`获得${formatInt(50)}个反物质星系。`'],
  ['`Get ${formatInt(50)} total Ra Celestial Memory levels.`', '`获得${formatInt(50)}拉天体记忆等级。`'],
  ['`Get ${formatInt(500)} total Ra Celestial Memory levels.`', '`获得${formatInt(500)}拉天体记忆等级。`'],
  ['`Get ${formatInt(800)} Antimatter Galaxies without`', '`获得${formatInt(800)}个反物质星系，且未`'],
  ['`buying 8th Antimatter Dimensions in your current Infinity.`', '`在当前无限中购买第八反物质维度。`'],
  ['`Get ${formatPostBreak("1e260000")} antimatter`', '`获得${formatPostBreak("1e260000")}反物质`'],
  ['`in ${formatInt(1)} minute or less while Dilated.`', '`在延时间状态下，${formatInt(1)}分钟或更短时间内。`'],
  ['`Get ${formatPostBreak(DC.D9_9999E9999, 4)} antimatter.`', '`获得${formatPostBreak(DC.D9_9999E9999, 4)}反物质。`'],
  ['`Get ${formatPostBreak(DC.E1E8)} antimatter while Dilated.`', '`在延时间状态下获得${formatPostBreak(DC.E1E8)}反物质。`'],
  ['`Get to Infinity with only a single 1st Antimatter Dimension without Dimension Boosts`', '`仅以一个第一反物质维度，不使用维度跃升达到无限`'],
  ['`or Antimatter Galaxies, while in the 2nd Antimatter Dimension Autobuyer Challenge.`', '`或反物质星系，在第二反物质维度自动购买挑战中。`'],
  ['`Have more Tachyon Particles than Dilated Time, with both exceeding ${format("1e5000", 2)}.`', '`超子微粒数量超过延时间，且二者均超过${format("1e5000", 2)}。`'],
  ['`Infinity in ${formatInt(1)} minute or less.`', '`${formatInt(1)}分钟或更短时间内完成无限。`'],
  ['`Infinity in ${formatInt(10)} minutes or less.`', '`${formatInt(10)}分钟或更短时间内完成无限。`'],
  ['`Infinity in under ${formatInt(2)} hours.`', '`${formatInt(2)}小时内完成无限。`'],
  ['`Infinity in under ${formatInt(250)}ms.`', '`${formatInt(250)}ms内完成无限。`'],
  ['`Infinity with just ${formatInt(1)} Antimatter Galaxy. (Your Antimatter Galaxies are reset on Infinity.)`', '`仅以${formatInt(1)}个反物质星系进行无限。(反物质星系在无限时重置。)`'],
  ['`Momentum increases ${formatX(10)} faster.`', '`动量提升速度加快${formatX(10)}倍。`'],
  ['`Multiply all Antimatter Dimensions by Ninety Degrees.`', '`以九十度乘所有反物质维度。`'],
  ['`Obtain ${formatInt(1000)} Free Tesseracts.`', '`获得${formatInt(1000)}个免费超立方体。`'],
  ['`Play for ${formatInt(8)} hours.`', '`游玩${formatInt(8)}小时。`'],
  ['`Reach ${format(1e12, 2, 2)} Endgames.`', '`达到${format(1e12, 2, 2)}终局。`'],
  ['`Reach ${format(1e6)} Infinity Power.`', '`达到${format(1e6)}无限之力。`'],
  ['`Reach ${format(DC.E12)} of all Antimatter Dimensions except the 8th.`', '`除第八维度外，所有反物质维度达到${format(DC.E12)}。`'],
  ['`Reach ${format(DC.E260)} Infinity Power.`', '`达到${format(DC.E260)}无限之力。`'],
  ['`Reach ${format(DC.E8)} Infinity Points per minute.`', '`每分钟无量点达到${format(DC.E8)}。`'],
  ['`Reach ${format(DC.E90)} Infinity Points without having any Infinities`', '`无任何无限的情况下，无量点达到${format(DC.E90)}`'],
  ['`or any 1st Antimatter Dimensions in your current Eternity.`', '`或当前永恒中无任何第一反物质维度。`'],
  ['`Reach ${format(DC.NUMMAX, 1, 0)} Celestial Points.`', '`天体点达到${format(DC.NUMMAX, 1, 0)}。`'],
  ['`Reach ${format(DC.NUMMAX, 1, 0)} Eternity Points.`', '`永点达到${format(DC.NUMMAX, 1, 0)}。`'],
  ['`Reach ${format(DC.NUMMAX, 1, 0)} Imaginary Machines.`', '`虚构机器达到${format(DC.NUMMAX, 1, 0)}。`'],
  ['`Reach ${format(DC.NUMMAX, 1, 0)} Reality Machines.`', '`真境机器达到${format(DC.NUMMAX, 1, 0)}。`'],
  ['`Reach ${formatPostBreak("1e15000")} Replicanti.`', '`复制元达到${formatPostBreak("1e15000")}。`'],
  ['`Reach ${formatPostBreak("1e22000")} Infinity Points without any Time Studies.`', '`无任何时间研究，无量点达到${formatPostBreak("1e22000")}。`'],
  ['`Reach ${formatPostBreak("1e26000")} Infinity Points without any Time Studies while Dilated.`', '`延时间状态下无任何时间研究，无量点达到${formatPostBreak("1e26000")}。`'],
  ['`Reach ${formatPostBreak("1e30008")} Infinity Points.`', '`无量点达到${formatPostBreak("1e30008")}。`'],
  ['`Reach ${formatPostBreak("1e35000")} antimatter.`', '`反物质达到${formatPostBreak("1e35000")}。`'],
  ['`Reach ${formatPostBreak("e1e10")} Replicanti.`', '`复制元达到${formatPostBreak("e1e10")}。`'],
  ['`Reach ${formatPostBreak("ee50")} Antimatter inside The Nameless Ones\' Reality.`', '`无名者真境内反物质达到${formatPostBreak("ee50")}。`'],
  ['`Reach ${formatPostBreak(DC.D9_99999E999, 5, 0)} Imaginary Machines.`', '`虚构机器达到${formatPostBreak(DC.D9_99999E999, 5, 0)}。`'],
  ['`Reach ${formatPostBreak(DC.D9_99999E999, 5, 0)} Infinity Points.`', '`无量点达到${formatPostBreak(DC.D9_99999E999, 5, 0)}。`'],
  ['`Reach ${formatPostBreak(DC.D9_99999E999, 5, 0)} Reality Machines.`', '`真境机器达到${formatPostBreak(DC.D9_99999E999, 5, 0)}。`'],
  ['`Reach ${formatPostBreak(DC.E200000)} Infinity Points without`', '`无量点达到${formatPostBreak(DC.E200000)}，且未`'],
  ['`buying any Infinity Dimensions or the ${formatX(2)} Infinity Point multiplier.`', '`购买任何无限维度或${formatX(2)}无量点倍率。`'],
  ['`Reach ${formatPostBreak(DC.E4000, 2)} Celestial Points of Eternity.`', '`永恒天体点达到${formatPostBreak(DC.E4000, 2)}。`'],
  ['`Reach ${formatPostBreak(DC.ENUMMAX, 2)} Antimatter.`', '`反物质达到${formatPostBreak(DC.ENUMMAX, 2)}。`'],
  ['`Reach ${formatPostBreak(Decimal.pow10(1e100), 2)} Antimatter outside Pelle.`', '`佩勒外反物质达到${formatPostBreak(Decimal.pow10(1e100), 2)}。`'],
  ['`Reach Eternity in Alpha\'s Reality.`', '`在阿尔法真境中达到永恒。`'],
  ['`Reach Infinity ${formatInt(10)} times.`', '`达到无限${formatInt(10)}次。`'],
  ['`Reach Infinity in Alpha\'s Reality.`', '`在阿尔法真境中达到无限。`'],
  ['`Reality for ${format(DC.NUMMAX, 1)} Reality Machines without having`', '`以${format(DC.NUMMAX, 1)}真境机器进行真境，且未`'],
  ['`any Charged Infinity Upgrades, having any equipped Glyphs, or buying any Triad Studies.`', '`装备任何充能无限升级、任何符文，或购买任何三元研究。`'],
  ['`Reality in under ${formatInt(5)} seconds (game time).`', '`${formatInt(5)}秒内完成真境(游戏时间)。`'],
  ['`Start with ${format(5e10)} antimatter.`', '`以${format(5e10)}反物质起始。`'],
  ['`Start with ${format(5e25)} antimatter.`', '`以${format(5e25)}反物质起始。`'],
  ['`Start with ${format(5e5)} antimatter.`', '`以${format(5e5)}反物质起始。`'],
  ['`Start with ${formatInt(5000)} antimatter.`', '`以${formatInt(5000)}反物质起始。`'],
  ['`The 3rd and higher Antimatter Dimensions are ${formatPercents(0.3)} stronger.`', '`第三及更高反物质维度强度提升${formatPercents(0.3)}。`'],
  ['`The 4th Antimatter Dimension is multiplied by ${formatInt(4)}.`', '`第四反物质维度乘以${formatInt(4)}。`'],
  ['`The 5th and higher Antimatter Dimensions are doubled.`', '`第五及更高反物质维度翻倍。`'],
  ['`Unlock Effarig\'s second shop.`', '`解锁埃法里格第二商店。`'],
  
  // Description strings with simple strings that were missed
  ['"Go Infinite."', '"达成无限。"'],
  // Missed reward strings
  ['"Multiply the 2nd Antimatter Dimension by the Antimatter Exponent."', '"以反物质指数乘第二反物质维度。"'],
  ['"Boost Celestial Point Gain."', '"提升天体点获取。"'],
  ['"Reach Eternity in Alpha\'s Reality."', '"在阿尔法真境中达到永恒。"'],
  ['"Start with ${formatInt(100)} antimatter."', '"以${formatInt(100)}反物质起始。"'],
];

let translated = 0;
let notFound = 0;

for (const [en, zh] of T) {
  if (content.includes(en)) {
    content = content.replace(en, zh);
    translated++;
  } else {
    notFound++;
  }
}

fs.writeFileSync(filepath, content, 'utf-8');

console.log(`Translated: ${translated}`);
console.log(`Not found: ${notFound}`);