const fs = require('fs');
const path = require('path');

const filepath = path.join(__dirname, 'src', 'core', 'secret-formula', 'achievements', 'normal-achievements.js');

let content = fs.readFileSync(filepath, 'utf-8');

// Second pass: handle template literals and remaining strings
const translations = [
  // Template literal versions (remaining)
  ['`Reach ${formatInt(1e6)} antimatter.`', '`达到 ${formatInt(1e6)} 反物质。`'],
  ['`Reach ${formatInt(1e9)} antimatter.`', '`达到 ${formatInt(1e9)} 反物质。`'],
  ['`Reach ${formatInt(1e12)} antimatter.`', '`达到 ${formatInt(1e12)} 反物质。`'],
  ['`Reach ${formatInt(1e15)} antimatter.`', '`达到 ${formatInt(1e15)} 反物质。`'],
  ['`Reach ${formatInt(1e18)} antimatter.`', '`达到 ${formatInt(1e18)} 反物质。`'],
  ['`Reach ${formatInt(1e21)} antimatter.`', '`达到 ${formatInt(1e21)} 反物质。`'],
  ['`Reach ${formatInt(1e24)} antimatter.`', '`达到 ${formatInt(1e24)} 反物质。`'],
  ['`Reach ${formatInt(1e27)} antimatter.`', '`达到 ${formatInt(1e27)} 反物质。`'],
  ['`Buy ${formatInt(10)}0 antimatter.`', '`购买 ${formatInt(10)}0 反物质。`'],
  ['`Buy ${formatInt(1e6)} antimatter.`', '`购买 ${formatInt(1e6)} 反物质。`'],
  ['`Buy ${formatInt(1e9)} antimatter.`', '`购买 ${formatInt(1e9)} 反物质。`'],
  ['`Buy ${formatInt(1e12)} antimatter.`', '`购买 ${formatInt(1e12)} 反物质。`'],
  ['`Buy ${formatInt(1e15)} antimatter.`', '`购买 ${formatInt(1e15)} 反物质。`'],
  ['`Buy ${formatInt(1e18)} antimatter.`', '`购买 ${formatInt(1e18)} 反物质。`'],
  ['`Buy ${formatInt(1e21)} antimatter.`', '`购买 ${formatInt(1e21)} 反物质。`'],
  ['`Buy ${formatInt(1e24)} antimatter.`', '`购买 ${formatInt(1e24)} 反物质。`'],
  ['`Buy ${formatInt(1e27)} antimatter.`', '`购买 ${formatInt(1e27)} 反物质。`'],
  ['`Buy ${formatInt(1e30)} antimatter.`', '`购买 ${formatInt(1e30)} 反物质。`'],
  ['`Buy ${formatInt(10)} Replicanti.`', '`购买 ${formatInt(10)} 复制元。`'],
  ['`Buy ${formatInt(1e4)} Replicanti.`', '`购买 ${formatInt(1e4)} 复制元。`'],
  ['`Buy ${formatInt(1e10)} Replicanti.`', '`购买 ${formatInt(1e10)} 复制元。`'],
  ['`Buy ${formatInt(1e25)} Replicanti.`', '`购买 ${formatInt(1e25)} 复制元。`'],
  ['`Reach ${formatInt(1e5)} antimatter without buying any Dimension Boosts or Antimatter Galaxies.`', '`不购买维度跃升或反物质星系，达到 ${formatInt(1e5)} 反物质。`'],
  ['`Get ${formatInt(1e4)} Replicanti within 10 seconds of buying the first one.`', '`购买第一个复制元后十秒内获得 ${formatInt(1e4)} 复制元。`'],
  ['`Get ${formatInt(250)} Replicanti.`', '`获得 ${formatInt(250)} 复制元。`'],
  ['`Get ${formatInt(1e7)} Replicanti.`', '`获得 ${formatInt(1e7)} 复制元。`'],
  ['`Get ${formatInt(1e14)} Replicanti.`', '`获得 ${formatInt(1e14)} 复制元。`'],
  ['`Get ${formatInt(1e28)} Replicanti.`', '`获得 ${formatInt(1e28)} 复制元。`'],
  ['`Reach ${formatInt(1e50)} Replicanti within 2 hours of buying the first one.`', '`购买第一个复制元后两小时内达到 ${formatInt(1e50)} 复制元。`'],
  ['`Get ${formatInt(10)}0 Replicanti for the 10th time, each time in less than 10 seconds.`', '`第十次获得 ${formatInt(10)}0 复制元，每次少于十秒。`'],
  ['`Reach ${formatInt(1e6)} Infinity Points.`', '`达到 ${formatInt(1e6)} 无量点。`'],
  ['`Reach ${formatInt(1e9)} Infinity Points.`', '`达到 ${formatInt(1e9)} 无量点。`'],
  ['`Reach ${formatInt(1e15)} Infinity Points.`', '`达到 ${formatInt(1e15)} 无量点。`'],
  ['`Reach ${formatInt(1e30)} Infinity Points.`', '`达到 ${formatInt(1e30)} 无量点。`'],
  ['`Reach ${formatInt(1e20)} Infinity Points without Time Dilation.`', '`不使用延时间，达到 ${formatInt(1e20)} 无量点。`'],
  ['`Reach ${formatInt(1e30)} Infinity Points without Time Dilation or Replicanti.`', '`不使用延时间或复制元，达到 ${formatInt(1e30)} 无量点。`'],
  ['`Reach ${formatInt(1e15)} Infinity Points without Replicanti.`', '`不使用复制元，达到 ${formatInt(1e15)} 无量点。`'],
  ['`Reach ${formatInt(1e5)} Infinity Points in under 10 minutes.`', '`十分钟内达到 ${formatInt(1e5)} 无量点。`'],
  ['`Reach ${formatInt(1e10)} Infinity Points in under 2 minutes 30 seconds.`', '`两分三十秒内达到 ${formatInt(1e10)} 无量点。`'],
  ['`Reach ${formatInt(1e20)} Infinity Points in under 5 minutes.`', '`五分钟内达到 ${formatInt(1e20)} 无量点。`'],
  ['`Reach ${formatInt(1e25)} Infinity Points in under 4 minutes.`', '`四分钟内达到 ${formatInt(1e25)} 无量点。`'],
  ['`Reach ${formatInt(1e30)} Infinity Points in under 3 minutes.`', '`三分钟内达到 ${formatInt(1e30)} 无量点。`'],
  ['`Reach ${formatInt(1e3)} Infinity Points per second.`', '`每秒产生 ${formatInt(1e3)} 无量点。`'],
  ['`Reach ${formatInt(1e6)} Infinity Points per second.`', '`每秒产生 ${formatInt(1e6)} 无量点。`'],
  ['`Reach ${formatInt(1e9)} Infinity Points per second.`', '`每秒产生 ${formatInt(1e9)} 无量点。`'],
  ['`Reach ${formatInt(1e15)} Infinity Points per second.`', '`每秒产生 ${formatInt(1e15)} 无量点。`'],
  ['`Reach ${formatInt(1e18)} Infinity Points per second.`', '`每秒产生 ${formatInt(1e18)} 无量点。`'],
  ['`Buy ${formatInt(5)}0 Time Dimensions.`', '`购买 ${formatInt(5)}0 时间维度。`'],
  ['`Buy ${formatInt(6)}0 Time Dimensions.`', '`购买 ${formatInt(6)}0 时间维度。`'],
  ['`Buy ${formatInt(7)}0 Time Dimensions.`', '`购买 ${formatInt(7)}0 时间维度。`'],
  ['`Buy ${formatInt(8)}0 Time Dimensions.`', '`购买 ${formatInt(8)}0 时间维度。`'],
  ['`Reach ${formatInt(1e18)} Infinity Points without Time Dimensions.`', '`不购买时间维度，达到 ${formatInt(1e18)} 无量点。`'],
  ['`Reach ${formatInt(1e21)} Infinity Points without Antimatter Galaxies.`', '`不购买反物质星系，达到 ${formatInt(1e21)} 无量点。`'],
  ['`Reach ${formatInt(1e18)} Infinity Points in less than 30 seconds.`', '`三十秒内达到 ${formatInt(1e18)} 无量点。`'],
  ['`Reach ${formatInt(1e21)} Infinity Points in less than 45 seconds.`', '`四十五秒内达到 ${formatInt(1e21)} 无量点。`'],
  ['`Reach ${formatInt(1e24)} Infinity Points in less than 60 seconds.`', '`六十秒内达到 ${formatInt(1e24)} 无量点。`'],
  ['`Reach ${formatInt(1e18)} Infinity Points without making a single purchase.`', '`不进行任何购买，达到 ${formatInt(1e18)} 无量点。`'],
  ['`Reach ${formatInt(1e21)} Infinity Points without buying a single Antimatter Dimension.`', '`不购买任何反物质维度，达到 ${formatInt(1e21)} 无量点。`'],
  ['`Get the amount of Time Shards that you would normally get in one hour in less than one second.`', '`不到一秒内获得通常一小时才能获得的时间碎片。`'],
  ['`Reach ${formatInt(1e13)} Infinity Points without having the 4th Antimatter Dimension autobuyer.`', '`无第四反物质维度自动购买的情况下，达到 ${formatInt(1e13)} 无量点。`'],
  ['`Reach ${formatInt(1e14)} Infinity Points without having the 5th Antimatter Dimension autobuyer.`', '`无第五反物质维度自动购买的情况下，达到 ${formatInt(1e14)} 无量点。`'],
  ['`Reach ${formatInt(1e16)} Infinity Points without having the 6th Antimatter Dimension autobuyer.`', '`无第六反物质维度自动购买的情况下，达到 ${formatInt(1e16)} 无量点。`'],
  ['`Reach ${formatInt(1e17)} Infinity Points without having the 7th Antimatter Dimension autobuyer.`', '`无第七反物质维度自动购买的情况下，达到 ${formatInt(1e17)} 无量点。`'],
  ['`Reach ${formatInt(1e19)} Infinity Points without having the 8th Antimatter Dimension autobuyer.`', '`无第八反物质维度自动购买的情况下，达到 ${formatInt(1e19)} 无量点。`'],
  ['`Reach ${formatInt(1e18)} Infinity Points.`', '`达到 ${formatInt(1e18)} 无量点。`'],
  ['`Reach ${formatInt(1e21)} Infinity Points.`', '`达到 ${formatInt(1e21)} 无量点。`'],
  ['`Reach ${formatInt(1e24)} Infinity Points.`', '`达到 ${formatInt(1e24)} 无量点。`'],
  ['`Reach ${formatInt(1e27)} Infinity Points.`', '`达到 ${formatInt(1e27)} 无量点。`'],
  ['`Reach ${formatInt(1e30)} Infinity Points.`', '`达到 ${formatInt(1e30)} 无量点。`'],
  ['`Get ${formatInt(1e5)} Eternity Points.`', '`获得 ${formatInt(1e5)} 永点。`'],
  ['`Get ${formatInt(1e8)} Eternity Points.`', '`获得 ${formatInt(1e8)} 永点。`'],
  ['`Get ${formatInt(1e12)} Eternity Points.`', '`获得 ${formatInt(1e12)} 永点。`'],
  ['`Get ${formatInt(1e15)} Eternity Points.`', '`获得 ${formatInt(1e15)} 永点。`'],
  ['`Get ${formatInt(1e20)} Eternity Points.`', '`获得 ${formatInt(1e20)} 永点。`'],
  ['`Get ${formatInt(1e25)} Eternity Points.`', '`获得 ${formatInt(1e25)} 永点。`'],
  ['`Get ${formatInt(1e30)} Eternity Points.`', '`获得 ${formatInt(1e30)} 永点。`'],
  ['`Get ${formatInt(1e35)} Eternity Points.`', '`获得 ${formatInt(1e35)} 永点。`'],
  ['`Get ${formatInt(1e40)} Eternity Points.`', '`获得 ${formatInt(1e40)} 永点。`'],
  ['`Get ${formatInt(1e45)} Eternity Points.`', '`获得 ${formatInt(1e45)} 永点。`'],
  ['`Get ${formatInt(1e50)} Eternity Points.`', '`获得 ${formatInt(1e50)} 永点。`'],
  ['`Get ${formatInt(1e5)} Eternity Points in less than an hour.`', '`一小时内获得 ${formatInt(1e5)} 永点。`'],
  ['`Get ${formatInt(1e15)} Eternity Points in less than 10 minutes.`', '`十分钟内获得 ${formatInt(1e15)} 永点。`'],
  ['`Get ${formatInt(1e30)} Eternity Points in less than 20 minutes.`', '`二十分钟内获得 ${formatInt(1e30)} 永点。`'],
  ['`Get ${formatInt(1e10)} Eternity Points without the 1st Time Dimension.`', '`无第一时间维度的情况下获得 ${formatInt(1e10)} 永点。`'],
  ['`Get ${formatInt(1e15)} Eternity Points without the 2nd Time Dimension.`', '`无第二时间维度的情况下获得 ${formatInt(1e15)} 永点。`'],
  ['`Get ${formatInt(1e20)} Eternity Points without the 3rd Time Dimension.`', '`无第三时间维度的情况下获得 ${formatInt(1e20)} 永点。`'],
  ['`Get ${formatInt(1e25)} Eternity Points without the 4th Time Dimension.`', '`无第四时间维度的情况下获得 ${formatInt(1e25)} 永点。`'],
  ['`Get ${formatInt(1e30)} Eternity Points without the 5th Time Dimension.`', '`无第五时间维度的情况下获得 ${formatInt(1e30)} 永点。`'],
  ['`Get ${formatInt(1e12)} Eternity Points without Time Dimensions.`', '`无时间维度的情况下获得 ${formatInt(1e12)} 永点。`'],
  ['`Get ${formatInt(1e15)} Eternity Points without buying Replicanti.`', '`不购买复制元的情况下获得 ${formatInt(1e15)} 永点。`'],
  ['`Get ${formatInt(1e18)} Eternity Points without Replicanti.`', '`无复制元的情况下获得 ${formatInt(1e18)} 永点。`'],
  ['`Get ${formatInt(1e21)} Eternity Points without Replicanti or Dilation.`', '`无复制元或延时间的情况下获得 ${formatInt(1e21)} 永点。`'],
  ['`Get ${formatInt(1e10)} Eternity Points without spending any Time Theorems.`', '`不消耗时间定理的情况下获得 ${formatInt(1e10)} 永点。`'],
  ['`Get ${formatInt(1e18)} Eternity Points.`', '`获得 ${formatInt(1e18)} 永点。`'],
  ['`Reach ${formatInt(1e10)} Eternity Points in under a minute.`', '`一分钟内达到 ${formatInt(1e10)} 永点。`'],
  ['`Reach ${formatInt(1e15)} Eternity Points in under a minute.`', '`一分钟内达到 ${formatInt(1e15)} 永点。`'],
  ['`Reach ${formatInt(1e15)} Eternity Points in under 30 seconds.`', '`三十秒内达到 ${formatInt(1e15)} 永点。`'],
  ['`Reach ${formatInt(1e3)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e3)} 永点。`'],
  ['`Reach ${formatInt(1e6)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e6)} 永点。`'],
  ['`Reach ${formatInt(1e9)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e9)} 永点。`'],
  ['`Reach ${formatInt(1e12)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e12)} 永点。`'],
  ['`Reach ${formatInt(1e15)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e15)} 永点。`'],
  ['`Reach ${formatInt(1e20)} Eternity Points per second.`', '`每秒产生 ${formatInt(1e20)} 永点。`'],
  ['`Reach ${formatInt(1e20)} Eternity Points.`', '`达到 ${formatInt(1e20)} 永点。`'],
  ['`Reach ${formatInt(1e25)} Eternity Points.`', '`达到 ${formatInt(1e25)} 永点。`'],
  ['`Reach ${formatInt(1e30)} Eternity Points.`', '`达到 ${formatInt(1e30)} 永点。`'],
  ['`Reach ${formatInt(1e35)} Eternity Points.`', '`达到 ${formatInt(1e35)} 永点。`'],
  ['`Reach ${formatInt(1e40)} Eternity Points.`', '`达到 ${formatInt(1e40)} 永点。`'],
  ['`Reach ${formatInt(1e45)} Eternity Points.`', '`达到 ${formatInt(1e45)} 永点。`'],
  ['`Reach ${formatInt(1e50)} Eternity Points.`', '`达到 ${formatInt(1e50)} 永点。`'],
  ['`Reach ${formatInt(1e55)} Eternity Points.`', '`达到 ${formatInt(1e55)} 永点。`'],
  ['`Reach ${formatInt(1e60)} Eternity Points.`', '`达到 ${formatInt(1e60)} 永点。`'],
  ['`Reach ${formatInt(1e65)} Eternity Points.`', '`达到 ${formatInt(1e65)} 永点。`'],
  ['`Reach ${formatInt(1e70)} Eternity Points.`', '`达到 ${formatInt(1e70)} 永点。`'],
  ['`Reach ${formatInt(1e75)} Eternity Points.`', '`达到 ${formatInt(1e75)} 永点。`'],
  ['`Reach ${formatInt(1e80)} Eternity Points.`', '`达到 ${formatInt(1e80)} 永点。`'],
  ['`Reach ${formatInt(1e85)} Eternity Points.`', '`达到 ${formatInt(1e85)} 永点。`'],
  ['`Reach ${formatInt(1e90)} Eternity Points.`', '`达到 ${formatInt(1e90)} 永点。`'],
  ['`Reach ${formatInt(1e95)} Eternity Points.`', '`达到 ${formatInt(1e95)} 永点。`'],
  ['`Reach ${formatInt(1e100)} Eternity Points.`', '`达到 ${formatInt(1e100)} 永点。`'],
  ['`Reach ${formatInt(1e105)} Eternity Points.`', '`达到 ${formatInt(1e105)} 永点。`'],
  ['`Reach ${formatInt(1e110)} Eternity Points.`', '`达到 ${formatInt(1e110)} 永点。`'],
  ['`Reach ${formatInt(1e115)} Eternity Points.`', '`达到 ${formatInt(1e115)} 永点。`'],
  ['`Reach ${formatInt(1e120)} Eternity Points.`', '`达到 ${formatInt(1e120)} 永点。`'],
  ['`Reach ${formatInt(1e125)} Eternity Points.`', '`达到 ${formatInt(1e125)} 永点。`'],
  ['`Reach ${formatInt(1e130)} Eternity Points.`', '`达到 ${formatInt(1e130)} 永点。`'],
  ['`Reach ${formatInt(1e135)} Eternity Points.`', '`达到 ${formatInt(1e135)} 永点。`'],
  ['`Reach ${formatInt(1e140)} Eternity Points.`', '`达到 ${formatInt(1e140)} 永点。`'],
  ['`Reach ${formatInt(1e145)} Eternity Points.`', '`达到 ${formatInt(1e145)} 永点。`'],
  ['`Reach ${formatInt(1e150)} Eternity Points.`', '`达到 ${formatInt(1e150)} 永点。`'],
  ['`Reach ${formatInt(1e155)} Eternity Points.`', '`达到 ${formatInt(1e155)} 永点。`'],
  ['`Reach ${formatInt(1e160)} Eternity Points.`', '`达到 ${formatInt(1e160)} 永点。`'],
  ['`Reach ${formatInt(1e165)} Eternity Points.`', '`达到 ${formatInt(1e165)} 永点。`'],
  ['`Reach ${formatInt(1e170)} Eternity Points.`', '`达到 ${formatInt(1e170)} 永点。`'],
  ['`Reach ${formatInt(1e175)} Eternity Points.`', '`达到 ${formatInt(1e175)} 永点。`'],
  ['`Reach ${formatInt(1e180)} Eternity Points.`', '`达到 ${formatInt(1e180)} 永点。`'],
  ['`Reach ${formatInt(1e185)} Eternity Points.`', '`达到 ${formatInt(1e185)} 永点。`'],
  ['`Reach ${formatInt(1e190)} Eternity Points.`', '`达到 ${formatInt(1e190)} 永点。`'],
  ['`Reach ${formatInt(1e195)} Eternity Points.`', '`达到 ${formatInt(1e195)} 永点。`'],
  ['`Reach ${formatInt(1e200)} Eternity Points.`', '`达到 ${formatInt(1e200)} 永点。`'],
  ['`Reach ${formatInt(1e5)} Reality Machines.`', '`达到 ${formatInt(1e5)} 真境机器。`'],
  ['`Reach ${formatInt(1e10)} Reality Machines.`', '`达到 ${formatInt(1e10)} 真境机器。`'],
  ['`Reach ${formatInt(1e15)} Reality Machines.`', '`达到 ${formatInt(1e15)} 真境机器。`'],
  ['`Reach ${formatInt(1e20)} Reality Machines.`', '`达到 ${formatInt(1e20)} 真境机器。`'],
  ['`Reach ${formatInt(1e25)} Reality Machines.`', '`达到 ${formatInt(1e25)} 真境机器。`'],
  ['`Reach ${formatInt(1e30)} Reality Machines.`', '`达到 ${formatInt(1e30)} 真境机器。`'],
  ['`Reach ${formatInt(1e40)} Reality Machines.`', '`达到 ${formatInt(1e40)} 真境机器。`'],
  ['`Reach ${formatInt(1e45)} Reality Machines.`', '`达到 ${formatInt(1e45)} 真境机器。`'],
  ['`Reach ${formatInt(1e50)} Reality Machines.`', '`达到 ${formatInt(1e50)} 真境机器。`'],
  ['`Reach ${formatInt(1e55)} Reality Machines.`', '`达到 ${formatInt(1e55)} 真境机器。`'],
  ['`Reach ${formatInt(1e60)} Reality Machines.`', '`达到 ${formatInt(1e60)} 真境机器。`'],
  ['`Reach ${formatInt(1e65)} Reality Machines.`', '`达到 ${formatInt(1e65)} 真境机器。`'],
  ['`Reach ${formatInt(1e10)} Reality Machines in under 10 minutes.`', '`十分钟内达到 ${formatInt(1e10)} 真境机器。`'],
  ['`Reach ${formatInt(1e20)} Reality Machines in under 15 minutes.`', '`十五分钟内达到 ${formatInt(1e20)} 真境机器。`'],
  ['`Reach ${formatInt(1e25)} Reality Machines in under 20 minutes.`', '`二十分钟内达到 ${formatInt(1e25)} 真境机器。`'],
  ['`Reach ${formatInt(1e25)} Reality Machines in under 15 minutes.`', '`十五分钟内达到 ${formatInt(1e25)} 真境机器。`'],
  ['`Reach ${formatInt(1e30)} Reality Machines in under 15 minutes.`', '`十五分钟内达到 ${formatInt(1e30)} 真境机器。`'],
  ['`Reach ${formatInt(1e30)} Reality Machines in under 5 minutes.`', '`五分钟内达到 ${formatInt(1e30)} 真境机器。`'],
  ['`Reach ${formatInt(1e35)} Reality Machines in under 10 minutes.`', '`十分钟内达到 ${formatInt(1e35)} 真境机器。`'],
  ['`Get the amount of Reality Machines that you would normally get in 10 minutes in 10 seconds.`', '`十秒内获得通常十分钟才能获得的真境机器。`'],
  ['`Reach ${formatInt(1e40)} Reality Machines.`', '`达到 ${formatInt(1e40)} 真境机器。`'],
  ['`Reach ${formatInt(1e45)} Reality Machines.`', '`达到 ${formatInt(1e45)} 真境机器。`'],
  ['`Reach ${formatInt(1e50)} Reality Machines.`', '`达到 ${formatInt(1e50)} 真境机器。`'],
  ['`Reach ${formatInt(1e55)} Reality Machines.`', '`达到 ${formatInt(1e55)} 真境机器。`'],
  ['`Reach ${formatInt(1e60)} Reality Machines.`', '`达到 ${formatInt(1e60)} 真境机器。`'],
  ['`Reach ${formatInt(1e65)} Reality Machines.`', '`达到 ${formatInt(1e65)} 真境机器。`'],
  ['`Reach ${formatInt(1e70)} Reality Machines.`', '`达到 ${formatInt(1e70)} 真境机器。`'],
  ['`Reach ${formatInt(1e75)} Reality Machines.`', '`达到 ${formatInt(1e75)} 真境机器。`'],
  ['`Reach ${formatInt(1e80)} Reality Machines.`', '`达到 ${formatInt(1e80)} 真境机器。`'],
  ['`Reach ${formatInt(1e85)} Reality Machines.`', '`达到 ${formatInt(1e85)} 真境机器。`'],
  ['`Reach ${formatInt(1e90)} Reality Machines.`', '`达到 ${formatInt(1e90)} 真境机器。`'],
  ['`Reach ${formatInt(1e95)} Reality Machines.`', '`达到 ${formatInt(1e95)} 真境机器。`'],
  ['`Reach ${formatInt(1e100)} Reality Machines.`', '`达到 ${formatInt(1e100)} 真境机器。`'],
  ['`Reach ${formatInt(1e105)} Reality Machines.`', '`达到 ${formatInt(1e105)} 真境机器。`'],
  ['`Reach ${formatInt(1e110)} Reality Machines.`', '`达到 ${formatInt(1e110)} 真境机器。`'],
  ['`Reach ${formatInt(1e115)} Reality Machines.`', '`达到 ${formatInt(1e115)} 真境机器。`'],
  ['`Reach ${formatInt(1e120)} Reality Machines.`', '`达到 ${formatInt(1e120)} 真境机器。`'],
  ['`Reach ${formatInt(1e125)} Reality Machines.`', '`达到 ${formatInt(1e125)} 真境机器。`'],
  ['`Reach ${formatInt(1e130)} Reality Machines.`', '`达到 ${formatInt(1e130)} 真境机器。`'],
  ['`Reach ${formatInt(1e135)} Reality Machines.`', '`达到 ${formatInt(1e135)} 真境机器。`'],
  ['`Reach ${formatInt(1e140)} Reality Machines.`', '`达到 ${formatInt(1e140)} 真境机器。`'],
  ['`Reach ${formatInt(1e145)} Reality Machines.`', '`达到 ${formatInt(1e145)} 真境机器。`'],
  ['`Reach ${formatInt(1e150)} Reality Machines.`', '`达到 ${formatInt(1e150)} 真境机器。`'],
  ['`Reach ${formatInt(1e155)} Reality Machines.`', '`达到 ${formatInt(1e155)} 真境机器。`'],
  ['`Reach ${formatInt(1e160)} Reality Machines.`', '`达到 ${formatInt(1e160)} 真境机器。`'],
  ['`Reach ${formatInt(1e165)} Reality Machines.`', '`达到 ${formatInt(1e165)} 真境机器。`'],
  ['`Reach ${formatInt(1e170)} Reality Machines.`', '`达到 ${formatInt(1e170)} 真境机器。`'],
  ['`Reach ${formatInt(1e175)} Reality Machines.`', '`达到 ${formatInt(1e175)} 真境机器。`'],
  ['`Reach ${formatInt(1e180)} Reality Machines.`', '`达到 ${formatInt(1e180)} 真境机器。`'],
  ['`Reach ${formatInt(1e185)} Reality Machines.`', '`达到 ${formatInt(1e185)} 真境机器。`'],
  ['`Reach ${formatInt(1e190)} Reality Machines.`', '`达到 ${formatInt(1e190)} 真境机器。`'],
  ['`Reach ${formatInt(1e195)} Reality Machines.`', '`达到 ${formatInt(1e195)} 真境机器。`'],
  ['`Reach ${formatInt(1e200)} Reality Machines.`', '`达到 ${formatInt(1e200)} 真境机器。`'],
  ['`Get ${formatInt(10)} Tachyon Particles.`', '`获得 ${formatInt(10)} 超子微粒。`'],
  ['`Get ${formatInt(100)} Tachyon Particles.`', '`获得 ${formatInt(100)} 超子微粒。`'],
  ['`Get ${formatInt(1e5)} Tachyon Particles.`', '`获得 ${formatInt(1e5)} 超子微粒。`'],
  ['`Get ${formatInt(1e10)} Tachyon Particles.`', '`获得 ${formatInt(1e10)} 超子微粒。`'],
  ['`Get ${formatInt(1e15)} Tachyon Particles.`', '`获得 ${formatInt(1e15)} 超子微粒。`'],
  ['`Get ${formatInt(1e20)} Tachyon Particles.`', '`获得 ${formatInt(1e20)} 超子微粒。`'],
  ['`Get ${formatInt(1e25)} Tachyon Particles.`', '`获得 ${formatInt(1e25)} 超子微粒。`'],
  ['`Get ${formatInt(1e30)} Tachyon Particles.`', '`获得 ${formatInt(1e30)} 超子微粒。`'],
  ['`Get ${formatInt(1e35)} Tachyon Particles.`', '`获得 ${formatInt(1e35)} 超子微粒。`'],
  ['`Get ${formatInt(1e40)} Tachyon Particles.`', '`获得 ${formatInt(1e40)} 超子微粒。`'],
  ['`Get ${formatInt(1e45)} Tachyon Particles.`', '`获得 ${formatInt(1e45)} 超子微粒。`'],
  ['`Get ${formatInt(1e50)} Tachyon Particles.`', '`获得 ${formatInt(1e50)} 超子微粒。`'],
  ['`Reach ${formatInt(1e15)} Tachyon Particles in less than 15 minutes.`', '`十五分钟内达到 ${formatInt(1e15)} 超子微粒。`'],
  ['`Reach ${formatInt(1e20)} Tachyon Particles in less than 10 minutes.`', '`十分钟内达到 ${formatInt(1e20)} 超子微粒。`'],
  ['`Reach ${formatInt(1e25)} Tachyon Particles in less than 5 minutes.`', '`五分钟内达到 ${formatInt(1e25)} 超子微粒。`'],
  ['`Reach ${formatInt(1e30)} Tachyon Particles in less than 10 minutes.`', '`十分钟内达到 ${formatInt(1e30)} 超子微粒。`'],
  ['`Reach ${formatInt(1e35)} Tachyon Particles in less than 5 minutes.`', '`五分钟内达到 ${formatInt(1e35)} 超子微粒。`'],
  ['`Reach ${formatInt(1e40)} Tachyon Particles in less than 3 minutes.`', '`三分钟内达到 ${formatInt(1e40)} 超子微粒。`'],
  ['`Get ${formatInt(1e45)} Tachyon Particles.`', '`获得 ${formatInt(1e45)} 超子微粒。`'],
  ['`Get ${formatInt(1e50)} Tachyon Particles.`', '`获得 ${formatInt(1e50)} 超子微粒。`'],
  ['`Get ${formatInt(1e55)} Tachyon Particles.`', '`获得 ${formatInt(1e55)} 超子微粒。`'],
  ['`Get ${formatInt(1e60)} Tachyon Particles.`', '`获得 ${formatInt(1e60)} 超子微粒。`'],
  ['`Get ${formatInt(1e65)} Tachyon Particles.`', '`获得 ${formatInt(1e65)} 超子微粒。`'],
  ['`Get ${formatInt(1e70)} Tachyon Particles.`', '`获得 ${formatInt(1e70)} 超子微粒。`'],
  ['`Get ${formatInt(1e75)} Tachyon Particles.`', '`获得 ${formatInt(1e75)} 超子微粒。`'],
  ['`Get ${formatInt(1e80)} Tachyon Particles.`', '`获得 ${formatInt(1e80)} 超子微粒。`'],
  ['`Get ${formatInt(1e85)} Tachyon Particles.`', '`获得 ${formatInt(1e85)} 超子微粒。`'],
  ['`Get ${formatInt(1e90)} Tachyon Particles.`', '`获得 ${formatInt(1e90)} 超子微粒。`'],
  ['`Get ${formatInt(1e95)} Tachyon Particles.`', '`获得 ${formatInt(1e95)} 超子微粒。`'],
  ['`Get ${formatInt(1e100)} Tachyon Particles.`', '`获得 ${formatInt(1e100)} 超子微粒。`'],
  ['`Get ${formatInt(1e105)} Tachyon Particles.`', '`获得 ${formatInt(1e105)} 超子微粒。`'],
  ['`Get ${formatInt(1e110)} Tachyon Particles.`', '`获得 ${formatInt(1e110)} 超子微粒。`'],
  ['`Get ${formatInt(1e115)} Tachyon Particles.`', '`获得 ${formatInt(1e115)} 超子微粒。`'],
  ['`Get ${formatInt(1e120)} Tachyon Particles.`', '`获得 ${formatInt(1e120)} 超子微粒。`'],
  ['`Get ${formatInt(1e125)} Tachyon Particles.`', '`获得 ${formatInt(1e125)} 超子微粒。`'],
  ['`Get ${formatInt(1e130)} Tachyon Particles.`', '`获得 ${formatInt(1e130)} 超子微粒。`'],
  ['`Get ${formatInt(1e135)} Tachyon Particles.`', '`获得 ${formatInt(1e135)} 超子微粒。`'],
  ['`Get ${formatInt(1e140)} Tachyon Particles.`', '`获得 ${formatInt(1e140)} 超子微粒。`'],
  ['`Get ${formatInt(1e145)} Tachyon Particles.`', '`获得 ${formatInt(1e145)} 超子微粒。`'],
  ['`Get ${formatInt(1e150)} Tachyon Particles.`', '`获得 ${formatInt(1e150)} 超子微粒。`'],
  ['`Get ${formatInt(1e155)} Tachyon Particles.`', '`获得 ${formatInt(1e155)} 超子微粒。`'],
  ['`Get ${formatInt(1e160)} Tachyon Particles.`', '`获得 ${formatInt(1e160)} 超子微粒。`'],
  ['`Get ${formatInt(1e165)} Tachyon Particles.`', '`获得 ${formatInt(1e165)} 超子微粒。`'],
  ['`Get ${formatInt(1e170)} Tachyon Particles.`', '`获得 ${formatInt(1e170)} 超子微粒。`'],
  ['`Get ${formatInt(1e175)} Tachyon Particles.`', '`获得 ${formatInt(1e175)} 超子微粒。`'],
  ['`Get ${formatInt(1e180)} Tachyon Particles.`', '`获得 ${formatInt(1e180)} 超子微粒。`'],
  ['`Get ${formatInt(1e185)} Tachyon Particles.`', '`获得 ${formatInt(1e185)} 超子微粒。`'],
  ['`Get ${formatInt(1e190)} Tachyon Particles.`', '`获得 ${formatInt(1e190)} 超子微粒。`'],
  ['`Get ${formatInt(1e195)} Tachyon Particles.`', '`获得 ${formatInt(1e195)} 超子微粒。`'],
  ['`Get ${formatInt(1e200)} Tachyon Particles.`', '`获得 ${formatInt(1e200)} 超子微粒。`'],
  ['`Buy ${formatInt(1e5)} Tachyon Particles without buying ${formatInt(1e20)} antimatter first.`', '`不先购买 ${formatInt(1e20)} 反物质而购买 ${formatInt(1e5)} 超子微粒。`'],
  ['`Buy ${formatInt(1e5)} Tachyon Particles without having spent any Time Theorems.`', '`未消耗任何时间定理即购买 ${formatInt(1e5)} 超子微粒。`'],
  ['`Get ${formatInt(1e3)} Tachyon Particles.`', '`获得 ${formatInt(1e3)} 超子微粒。`'],
  ['`Get ${formatInt(1e4)} Tachyon Particles.`', '`获得 ${formatInt(1e4)} 超子微粒。`'],
  ['`Get ${formatInt(1e5)} Tachyon Particles.`', '`获得 ${formatInt(1e5)} 超子微粒。`'],
  ['`Get ${formatInt(1e6)} Tachyon Particles.`', '`获得 ${formatInt(1e6)} 超子微粒。`'],
  ['`Get ${formatInt(1e7)} Tachyon Particles.`', '`获得 ${formatInt(1e7)} 超子微粒。`'],
  ['`Get ${formatInt(1e8)} Tachyon Particles.`', '`获得 ${formatInt(1e8)} 超子微粒。`'],
  ['`Get ${formatInt(1e9)} Tachyon Particles.`', '`获得 ${formatInt(1e9)} 超子微粒。`'],
  ['`Get ${formatInt(1e10)} Tachyon Particles.`', '`获得 ${formatInt(1e10)} 超子微粒。`'],
  ['`Get ${formatInt(1e11)} Tachyon Particles.`', '`获得 ${formatInt(1e11)} 超子微粒。`'],
  ['`Get ${formatInt(1e12)} Tachyon Particles.`', '`获得 ${formatInt(1e12)} 超子微粒。`'],
  ['`Get ${formatInt(1e13)} Tachyon Particles.`', '`获得 ${formatInt(1e13)} 超子微粒。`'],
  ['`Get ${formatInt(1e14)} Tachyon Particles.`', '`获得 ${formatInt(1e14)} 超子微粒。`'],
  ['`Get ${formatInt(1e15)} Tachyon Particles.`', '`获得 ${formatInt(1e15)} 超子微粒。`'],
  ['`Get ${formatInt(1e16)} Tachyon Particles.`', '`获得 ${formatInt(1e16)} 超子微粒。`'],
  ['`Get ${formatInt(1e17)} Tachyon Particles.`', '`获得 ${formatInt(1e17)} 超子微粒。`'],
  ['`Get ${formatInt(1e18)} Tachyon Particles.`', '`获得 ${formatInt(1e18)} 超子微粒。`'],
  ['`Get ${formatInt(1e19)} Tachyon Particles.`', '`获得 ${formatInt(1e19)} 超子微粒。`'],
  ['`Get ${formatInt(1e20)} Tachyon Particles.`', '`获得 ${formatInt(1e20)} 超子微粒。`'],
  ['`Get ${formatInt(1e21)} Tachyon Particles.`', '`获得 ${formatInt(1e21)} 超子微粒。`'],
  ['`Get ${formatInt(1e22)} Tachyon Particles.`', '`获得 ${formatInt(1e22)} 超子微粒。`'],
  ['`Get ${formatInt(1e23)} Tachyon Particles.`', '`获得 ${formatInt(1e23)} 超子微粒。`'],
  ['`Get ${formatInt(1e24)} Tachyon Particles.`', '`获得 ${formatInt(1e24)} 超子微粒。`'],
  ['`Get ${formatInt(1e25)} Tachyon Particles.`', '`获得 ${formatInt(1e25)} 超子微粒。`'],
  ['`Get ${formatInt(1e26)} Tachyon Particles.`', '`获得 ${formatInt(1e26)} 超子微粒。`'],
  ['`Get ${formatInt(1e27)} Tachyon Particles.`', '`获得 ${formatInt(1e27)} 超子微粒。`'],
  ['`Get ${formatInt(1e28)} Tachyon Particles.`', '`获得 ${formatInt(1e28)} 超子微粒。`'],
  ['`Get ${formatInt(1e29)} Tachyon Particles.`', '`获得 ${formatInt(1e29)} 超子微粒。`'],
  ['`Get ${formatInt(1e30)} Tachyon Particles.`', '`获得 ${formatInt(1e30)} 超子微粒。`'],
  ['`You cannot buy Galaxies or have the Galaxy autobuyer.`', '`不可购买星系或拥有星系自动购买。`'],
  ['`You cannot have Replicanti or any of the Replicanti upgrades.`', '`不可拥有复制元或任何复制元升级。`'],
  ['`You cannot have Time Dilation or Dilated Time.`', '`不可拥有时间膨胀或延时间。`'],
  ['`You cannot have Time Dimensions or the 1st Time Dimension autobuyer.`', '`不可拥有时间维度或第一时间维度自动购买。`'],
  ['`You cannot have Replicanti.`', '`不可拥有复制元。`'],
  ['`You cannot have the autobuyer for the 8th Time Dimension.`', '`不可拥有第八时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 7th Time Dimension.`', '`不可拥有第七时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 6th Time Dimension.`', '`不可拥有第六时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 5th Time Dimension.`', '`不可拥有第五时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 4th Time Dimension.`', '`不可拥有第四时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 3rd Time Dimension.`', '`不可拥有第三时间维度的自动购买。`'],
  ['`You cannot have the autobuyer for the 2nd Time Dimension.`', '`不可拥有第二时间维度的自动购买。`'],
  ['`Reach ${formatInt(1e5)} IP without TDs`', '`无时间维度达到 ${formatInt(1e5)} 无量点`'],
  ['`Reach ${formatInt(1e8)} IP without TDs`', '`无时间维度达到 ${formatInt(1e8)} 无量点`'],
  ['`Reach ${formatInt(1e11)} IP without TDs`', '`无时间维度达到 ${formatInt(1e11)} 无量点`'],
  ['`Reach ${formatInt(1e14)} IP without TDs`', '`无时间维度达到 ${formatInt(1e14)} 无量点`'],
  ['`Reach ${formatInt(1e17)} IP without TDs`', '`无时间维度达到 ${formatInt(1e17)} 无量点`'],
  ['`Reach ${formatInt(1e5)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e5)} 永点`'],
  ['`Reach ${formatInt(1e10)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e10)} 永点`'],
  ['`Reach ${formatInt(1e15)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e15)} 永点`'],
  ['`Reach ${formatInt(1e20)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e20)} 永点`'],
  ['`Reach ${formatInt(1e25)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e25)} 永点`'],
  ['`Reach ${formatInt(1e30)} EP in Eternity Challenge 8`', '`永恒挑战八中达到 ${formatInt(1e30)} 永点`'],
  ['`Get ${formatInt(1e5)} Tachyon Particles before ${formatInt(1e5)} Replicanti.`', '`先于 ${formatInt(1e5)} 复制元获得 ${formatInt(1e5)} 超子微粒。`'],
  ['`Complete all Eternity Challenges under ${formatInt(1e4)} EP.`', '`在 ${formatInt(1e4)} 永点以下完成所有永恒挑战。`'],
  ['`Buy a ${formatInt(1e8)}0 Reality.`', '`购买一个 ${formatInt(1e8)}0 真境。`'],
  ['`Get ${formatInt(1e8)} Tachyon Particles with only the first Reality Glyph type equipped.`', '`仅装备第一真境符文类型时获得 ${formatInt(1e8)} 超子微粒。`'],
  ['`Get ${formatInt(1e15)} Tachyon Particles with only the second Reality Glyph type equipped.`', '`仅装备第二真境符文类型时获得 ${formatInt(1e15)} 超子微粒。`'],
  ['`Get ${formatInt(1e25)} Tachyon Particles with only the third Reality Glyph type equipped.`', '`仅装备第三真境符文类型时获得 ${formatInt(1e25)} 超子微粒。`'],
  ['`Get ${formatInt(1e35)} Tachyon Particles with only the fourth Reality Glyph type equipped.`', '`仅装备第四真境符文类型时获得 ${formatInt(1e35)} 超子微粒。`'],
  ['`Get ${formatInt(1e45)} Tachyon Particles with only the fifth Reality Glyph type equipped.`', '`仅装备第五真境符文类型时获得 ${formatInt(1e45)} 超子微粒。`'],
  ['`Purchase both Black Holes at least once.`', '`至少购买两个黑洞各一次。`'],
  ['`Buy a ${formatInt(1e10)}0 Reality without Time Dilation.`', '`不使用时间膨胀，购买一个 ${formatInt(1e10)}0 真境。`'],
  ['`Buy a ${formatInt(1e20)}0 Reality without Time Dilation, Replicanti, or Dimensional Sacrifice.`', '`不使用时间膨胀、复制元或维度献祭，购买一个 ${formatInt(1e20)}0 真境。`'],
  ['`Reach ${formatInt(1e40)} Reality Machines without the Time Dimension dimension autobuyer.`', '`无时间维度自动购买的情况下达到 ${formatInt(1e40)} 真境机器。`'],
  ['`Reach ${formatInt(1e50)} Reality Machines without any Time Dimension autobuyers.`', '`无任何时间维度自动购买的情况下达到 ${formatInt(1e50)} 真境机器。`'],
  ['`Buy a ${formatInt(1e5)}00 Reality without any Time Theorems purchased.`', '`未购买任何时间定理的情况下，购买一个 ${formatInt(1e5)}00 真境。`'],
  ['`Reach ${formatInt(1e35)} Reality Machines.`', '`达到 ${formatInt(1e35)} 真境机器。`'],
  ['`Get the amount of Reality Machines that you would normally get in 10 minutes in 10 seconds.`', '`十秒内获得通常十分钟才能获得的真境机器。`'],
  ['`Buy a ${formatInt(1e10)}0 Reality.`', '`购买一个 ${formatInt(1e10)}0 真境。`'],
  ['`Get ${formatInt(1e40)} Tachyon Particles.`', '`获得 ${formatInt(1e40)} 超子微粒。`'],
  ['`Buy a ${formatInt(1e8)}0 Reality without buying Black Holes.`', '`不购买黑洞，购买一个 ${formatInt(1e8)}0 真境。`'],
  ['`Buy a ${formatInt(1e20)}0 Reality.`', '`购买一个 ${formatInt(1e20)}0 真境。`'],
  ['`Get a Singularity in each of the first six rows of the Singularity tree.`', '`在奇点树前六行中每行获得一个奇点。`'],
  ['`Buy a ${formatInt(1e30)}0 Reality.`', '`购买一个 ${formatInt(1e30)}0 真境。`'],
  ['`Get ${formatInt(1e45)} Tachyon Particles.`', '`获得 ${formatInt(1e45)} 超子微粒。`'],
  ['`Get ${formatInt(1e50)} Tachyon Particles.`', '`获得 ${formatInt(1e50)} 超子微粒。`'],
  ['`Get ${formatInt(1e55)} Tachyon Particles.`', '`获得 ${formatInt(1e55)} 超子微粒。`'],
  ['`Get ${formatInt(1e60)} Tachyon Particles.`', '`获得 ${formatInt(1e60)} 超子微粒。`'],
  ['`Get ${formatInt(1e65)} Tachyon Particles.`', '`获得 ${formatInt(1e65)} 超子微粒。`'],
  ['`Get ${formatInt(1e70)} Tachyon Particles.`', '`获得 ${formatInt(1e70)} 超子微粒。`'],
  ['`Get ${formatInt(1e75)} Tachyon Particles.`', '`获得 ${formatInt(1e75)} 超子微粒。`'],
  ['`Get ${formatInt(1e80)} Tachyon Particles.`', '`获得 ${formatInt(1e80)} 超子微粒。`'],
  ['`Get ${formatInt(1e85)} Tachyon Particles.`', '`获得 ${formatInt(1e85)} 超子微粒。`'],
  ['`Get ${formatInt(1e90)} Tachyon Particles.`', '`获得 ${formatInt(1e90)} 超子微粒。`'],
  ['`Get ${formatInt(1e95)} Tachyon Particles.`', '`获得 ${formatInt(1e95)} 超子微粒。`'],
  ['`Get ${formatInt(1e100)} Tachyon Particles.`', '`获得 ${formatInt(1e100)} 超子微粒。`'],
  ['`Get ${formatInt(1e105)} Tachyon Particles.`', '`获得 ${formatInt(1e105)} 超子微粒。`'],
  ['`Get ${formatInt(1e110)} Tachyon Particles.`', '`获得 ${formatInt(1e110)} 超子微粒。`'],
  ['`Get ${formatInt(1e115)} Tachyon Particles.`', '`获得 ${formatInt(1e115)} 超子微粒。`'],
  ['`Get ${formatInt(1e120)} Tachyon Particles.`', '`获得 ${formatInt(1e120)} 超子微粒。`'],
  ['`Get ${formatInt(1e125)} Tachyon Particles.`', '`获得 ${formatInt(1e125)} 超子微粒。`'],
  ['`Get ${formatInt(1e130)} Tachyon Particles.`', '`获得 ${formatInt(1e130)} 超子微粒。`'],
  ['`Get ${formatInt(1e135)} Tachyon Particles.`', '`获得 ${formatInt(1e135)} 超子微粒。`'],
  ['`Get ${formatInt(1e140)} Tachyon Particles.`', '`获得 ${formatInt(1e140)} 超子微粒。`'],
  ['`Get ${formatInt(1e145)} Tachyon Particles.`', '`获得 ${formatInt(1e145)} 超子微粒。`'],
  ['`Get ${formatInt(1e150)} Tachyon Particles.`', '`获得 ${formatInt(1e150)} 超子微粒。`'],
  ['`Get ${formatInt(1e155)} Tachyon Particles.`', '`获得 ${formatInt(1e155)} 超子微粒。`'],
  ['`Get ${formatInt(1e160)} Tachyon Particles.`', '`获得 ${formatInt(1e160)} 超子微粒。`'],
  ['`Get ${formatInt(1e165)} Tachyon Particles.`', '`获得 ${formatInt(1e165)} 超子微粒。`'],
  ['`Get ${formatInt(1e170)} Tachyon Particles.`', '`获得 ${formatInt(1e170)} 超子微粒。`'],
  ['`Get ${formatInt(1e175)} Tachyon Particles.`', '`获得 ${formatInt(1e175)} 超子微粒。`'],
  ['`Get ${formatInt(1e180)} Tachyon Particles.`', '`获得 ${formatInt(1e180)} 超子微粒。`'],
  ['`Get ${formatInt(1e185)} Tachyon Particles.`', '`获得 ${formatInt(1e185)} 超子微粒。`'],
  ['`Get ${formatInt(1e190)} Tachyon Particles.`', '`获得 ${formatInt(1e190)} 超子微粒。`'],
  ['`Get ${formatInt(1e195)} Tachyon Particles.`', '`获得 ${formatInt(1e195)} 超子微粒。`'],
  ['`Get ${formatInt(1e200)} Tachyon Particles.`', '`获得 ${formatInt(1e200)} 超子微粒。`'],
];

let translated = 0;
let notFound = 0;

for (const [en, zh] of translations) {
  if (content.includes(en)) {
    content = content.replace(en, zh);
    translated++;
  } else {
    notFound++;
  }
}

fs.writeFileSync(filepath, content, 'utf-8');

console.log(`Translated (pass 2): ${translated}`);
console.log(`Not found (pass 2): ${notFound}`);