import sys

filepath = 'src/core/secret-formula/achievements/normal-achievements.js'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

T = {}

def t(en, zh):
    T[en] = zh

# === ACHIEVEMENT NAMES ===
t('You gotta start somewhere', '万物伊始')
t('100 antimatter is a lot', '微末之数亦为巨')
t('Half life 3 CONFIRMED', '半衰期三已验')
t('L4D: Left 4 Dimensions', '四维之役')
t('5 Dimension Antimatter Punch', '五维一击')
t("We couldn't afford 9", '九亦足矣')
t('Not a luck related achievement', '非关幸运')
t('90 degrees to infinity', '零度至无限')
t('To infinity!', '向无限进发！')
t('FAKE NEWS!', '虚妄之谈！')
t('The 9th Dimension is a lie', '第九维度皆是虚妄')
t('Antimatter Apocalypse', '反物质末日')
t('Boosting to the max', '维升至极')
t('You got past The Big Wall', '逾越巨壁')
t('Double Galaxy', '双重星系')
t("There's no point in doing that...", '徒劳无功之举……')
t('I forgot to nerf that', '忘削其力')
t('The Gods are pleased', '诸神欣悦')
t("That's a lot of infinites", '无限之数甚矣')
t('You did not need it anyway', '本无所用')
t('Daredevil', '铤而走险')
t('Faster than a potato', '速逾薯步')
t('Multidimensional', '多维并行')
t('Antichallenged', '反挑战')
t('Limit Break', '破限')
t('Age of Automation', '自动时代')
t('Definitely not worth it', '得不偿失')
t("That's FASTER!", '迅捷如斯！')
t('Forever is not that long', '永恒几何')
t('Many Deaths', '殒落数次')
t('Gift from the Gods', '天赐神恩')
t('This is fine.', '此亦无碍。')
t('Bulked Up', '批量倍增')
t('Oh, hey... You are still here?', '哦……你还在此处？')
t('A new beginning', '新的开端')
t('Zero Deaths', '零殒')
t('Not-so-challenging', 'chalenge 虚名')
t('Faster than a squared potato', '速逾薯方')
t('Infinitely Challenging', '无限挑战')
t('You did this again just for the achievement right?', '再战只为成就乎？')
t('ERROR 909: Dimension not found', '错误909：维度未觅')
t("Can't hold all these infinities", '无限难承')
t('THIS ACHIEVEMENT DOES NOT EXIST', '此成就本不存在')
t('Not a second lost', '分秒必争')
t('NEW DIMENSIONS???', '新维度降临？？？')
t('One for each dimension', '每维其一')
t('1 Million is a lot', '百万亦巨')
t('Blink of an eye', '转瞬之间')
t('Game Design Is My Passion', '设计之热')
t('Anti-antichallenged', '反-反挑战')
t('YOU CAN GET 50 GALAXIES?!?!', '汝能得五十星系？！')
t('I got a few to spare', '略有富余')
t('ALL YOUR IP ARE BELONG TO US', '无量点尽归吾属')
t('Do you even bend time bro?', '汝弯曲时间乎？')
t('2 MILLION INFINITIES', '二百万无限')
t('Yet another infinity reference', '又一无限之典')
t('Ludicrous Speed', '极速绝伦')
t('I brake for NOBODY!', '无人可挡！')
t('MAXIMUM OVERDRIVE', '极限过载')
t('4.3333 minutes of Infinity', '四分三之无限')
t('Is this safe?', '此安全乎？')
t('Time is relative', '时间相对')
t('Like jumping on a lego', '踏石之跃')
t('This mile took an eternity', '此路漫漫若永恒')
t("Tätä saavutusta ei ole olemassa II", '此成就本不存在 II')
t("Cet accomplissement n'existe pas III", '此成就本不存在 III')
t("Este logro no existe IV", '此成就本不存在 IV')
t('That was not an eternity', '此非永恒')
t('Infinite Time', '无限时间')
t('The swarm', '蜂拥而至')
t('Do you really need a guide for this?', '岂需指引？')
t('We COULD afford 9', '九亦能承')
t('Yo dawg, I heard you liked infinities...', '喜闻君爱无限……')
t('Never again', '永不再来')
t('Eternities are the new infinity', '永恒即新无限')
t("You're a mistake", '汝为谬误')
t('I wish I had gotten 7 eternities', '愿得七永恒')
t('Do I really need to infinity', '岂必无限')
t('Costco sells Dimboosts now!', '量贩维度跃升！')
t("IT'S OVER 9000", '逾九千')
t('Can you get infinite IP?', '能得无量点无限乎？')
t("You're already dead.", '汝已死矣。')
t('5 more eternities until the update', '五永恒以待更新')
t('Long lasting relationship', '持久之契')
t('Like feasting on a behind', '享食其后')
t('Popular music', '流行之乐')
t('But I wanted another prestige layer...', '别求新阶……')
t('What do I have to do to get rid of you', '如何方能去汝')
t('No ethical consumption', '无有操守')
t('Unique snowflakes', '独此一片')
t('I never liked this infinity stuff anyway', '本不喜此无限之事')
t('When will it be enough?', '何时方足？')
t('Faster than a potato^286078', '速逾薯之幂')
t('I told you already, time is relative', '已告汝，时间相对')
t('Now you are thinking with dilation!', '今以延时间思维！')
t('This is what I have to do to get rid of you.', '此乃去汝之法。')
t('Snap back to reality', '回到真境')
t('How does this work?', '此作何用？')
t('Yo dawg, I heard you liked reskins...', '喜闻君爱翻新……')
t('Is this an Interstellar reference?', '此乃星际之典乎？')
t('Have all Perks bought.', '购得所有天赋。')
t('Master of Reality', '真境之主')
t('Royal flush', '同花顺')
t('You really did not need it anyway', '本无所用')
t("Y'all got any more of them Glyphs?", '还有符文否？')
t('More like "reallydoesn\'tmatter"', '实无关紧要')
t('I am speed', '我即速度')
t('Achievement #15983', '成就第一五九八三')
t('College Dropout', '大学辍学')
t("It's super effective!", '此效甚著！')
t('Bruh, are you like, inside the hole?', '汝在穴中乎？')
t("that's where you're wrong kiddo", '汝误矣，童子')
t('Reinstalled the game and rejoined the server', '重装重连')
t('Actually, super easy! Barely an inconvenience!', '实乃易事！')
t('Infinity times two', '无限倍二')
t('Perfectly balanced', '完美平衡')
t('Nicenice.', '好好。')
t('Mr. Layer? Sorry, you are not on the list', '层先生？汝不在榜')
t('Woah, we are halfway there', '哇，已及半途')
t('The god is delighted', '神大悦')
t("Hitchhiker's Guide to Reality", '真境搭车指南')
t("Cet accomplissement n'existe pas III", '此成就本不存在 III')
t("Don't you already have two of these?", '汝不已有二？')
t('Get a Singularity.', '得一奇点。')
t('The First Antihistorian', '第一反史学家')
t('Mom counted to 3', '母数至三')
t('This mile took a celestial', '此路需一天体')
t('Destroyer of Worlds', '世界毁灭者')
t('Antimatter Dimensions Eternal', '反物质维度永恒')
t('One more time', '再一次')
t('Déjà vOoM', '既视感')
t("You're out!", '汝出局！')
t('Four score and seven years ago', 'Four score and seven years ago')
t('An unhealthy obsession', '痴迷不悟')
t('The One with Dilated Time', '延时间之章')
t('The End...', '终结……')
t('...For Now', '……暂此')
t('Destiny', '宿命')
t('Unstoppable', '势不可挡')
t('TIME. IS. RELATIVE.', '时间。乃。相对。')
t('System Error', '系统错误')
t('At Long Last', '终至')
t('Wait. That is illegal.', '此乃非法。')
t('...eons stacked on eons stacked on...', '……亿万年复亿万年……')
t('A Newer Beginning', '新之开端')
t('Reinstalled the game and rejoined the server... again', '重装重连……再一次')
t('Faster than a dilated potato', '速逾延时间之薯')
t('Hard Reset', '硬核重置')
t('Look to the Stars', '仰望星辰')
t('Full Control of the Dark', '执暗之权')
t('Gone...', '逝去……')
t('...But Not Forgotten', '……然未忘怀')
t('Mistake?', '谬误？')
t('The Dark Crunch', '暗之坍缩')
t('Never Gonna Stop', '永不止息')
t('IT WILL NEVER BE ENOUGH.', '永无餍足。')
t('Domain Error', '域错误')
t('Este logro no existe IV', '此成就本不存在 IV')
t('Why are we still here...', '为何犹在……')
t('...just to suffer?', '……徒受此苦？')
t('Light', '光')
t('Time is absolute', '时间绝对')
t('Power! Unlimited Power!', '力！无限之力！')
t('Destroyer of Universes', '宇宙毁灭者')
t('299792458m/s', '光速')
t('Thirty thousand degrees', '三万度')
t('How do these work???', '此作何用？？？')
t('Look how far we have come', '回顾来路')
t('Grandmastery', '至极大师')
t('Millenium of peace', '千年太平')
t('End of an era', '时代终结')
t('The One with Celestial Time', '天体时间之章')
t('Never-ending Darkness', '无尽黑暗')
t('Supernova', '超新星')
t('Hypernova', '极超新星')
t('Limits of Reality', '真境之限')

# === DESCRIPTIONS ===
t('Buy a 1st Antimatter Dimension.', '购买第一个反物质维度。')
t('Buy a 2nd Antimatter Dimension.', '购买第二个反物质维度。')
t('Buy a 3rd Antimatter Dimension.', '购买第三个反物质维度。')
t('Buy a 4th Antimatter Dimension.', '购买第四个反物质维度。')
t('Buy a 5th Antimatter Dimension.', '购买第五个反物质维度。')
t('Buy a 6th Antimatter Dimension.', '购买第六个反物质维度。')
t('Buy a 7th Antimatter Dimension.', '购买第七个反物质维度。')
t('Buy an 8th Antimatter Dimension.', '购买第八个反物质维度。')
t('Go Infinite.', '进行无限。')
t('Break Infinity.', '破碎无限。')
t('Go Eternal.', '进行永恒。')
t('Make a new Reality.', '创造新真境。')
t('Unlock the automator.', '解锁自动化装置。')
t('Unlock the Black Hole.', '解锁黑洞。')
t('Have either Black Hole interval smaller than its duration.', '黑洞间隔小于持续时间。')
t('Have all Perks bought.', '购得所有天赋。')
t('Have all Reality upgrades bought.', '购得所有真境升级。')
t('Reality with one of each basic Glyph type.', '以每种基础符文各一进行真境。')
t('Get a Singularity.', '得一奇点。')
t('Annihilate your Dark Matter Dimensions.', '湮灭暗物质维度。')
t('Complete all Singularity Milestones in the first six rows at least once.', '完成前六行所有奇点里程碑至少一次。')
t('Doom your Reality.', '毁灭汝之真境。')
t('Permanently gain back all Antimatter Dimension autobuyers.', '永久恢复所有反物质维度自动购买。')
t('Complete Infinity Challenge 5 while Doomed.', '毁灭中完成无限挑战五。')
t('Encounter the third Pelle Strike.', '遭遇第三佩勒之击。')
t('Encounter the fourth Pelle Strike.', '遭遇第四佩勒之击。')
t("Purchase Time Study 181 while Doomed.", '毁灭中购入时间研究181。')
t('Unlock Dilation while Doomed.', '毁灭中解锁延时间。')
t('Escape the Doomed Reality.', '逃离毁灭真境。')
t('Purchase a 1st Dimension in Run 2.', '第二轮购入第一维度。')
t('Doom Your Reality in Run 2.', '第二轮毁灭汝之真境。')
t('Beat Doom in Run 2.', '第二轮击败毁灭。')
t('Break Eternity.', '破碎永恒。')
t('Endgame in under an hour.', '一小时内完成终局。')
t('Regain all Achievements in Pelle.', '在佩勒中重获所有成就。')
t('Own a Reality Glyph of level ', '拥有等级 ')
t(' or higher.', ' 或更高的真境符文。')
t('Have a game speed of ', '拥有 ')
t(' with Celestial Matter toggled off.', ' 使天体物质关闭时的游戏速度。')
t('Begin generation of Galactic Power.', '开始产生银河之力。')
t('Have every Endgame Mastery at once.', '同时拥有所有终局精通。')
t('Disable all Pelle Nerfs.', '禁用所有佩勒削弱。')
t('Enter the Ethereal.', '进入以太。')
t('Purchase the 8th Dark Matter Dimension.', '购入第八暗物质维度。')
t('Destroy Pelle.', '毁灭佩勒。')
t('Reach ', '达成 ')
t(' Imaginary Machines.', ' 虚数机器。')
t('Enter Alpha\'s Reality.', '进入阿尔法真境。')
t('Reach Infinity in Alpha\'s Reality.', '在阿尔法真境中达成无限。')
t('Reach Eternity in Alpha\'s Reality.', '在阿尔法真境中达成永恒。')
t('Reach ', '达成 ')
t(' Celestial Points.', ' 天体点。')
t('Reach ', '达成 ')
t(' Antimatter inside The Nameless Ones\' Reality.', ' 无名者真境中的反物质。')
t('Defeat Alpha.', '击败阿尔法。')
t('Have more Tachyon Particles than Dilated Time, with both exceeding ', '拥有超过延时间的超子微粒，且二者均逾 ')
t('Momentum increases ', '动量增加 ')
t(' faster.', ' 倍速。')
t('Have your Infinity Dimension purchase cap exceed ', '无限维度购买上限逾 ')
t('Infinity Upgrades stay charged on Endgame.', '无限升级在终局时保持充能。')
t('Reach ', '达成 ')
t(' Antimatter outside Pelle.', ' 佩勒之外的反物质。')
t('Uncap Celestial Matter.', '解锁天体物质上限。')
t('Reduce the Celestial Matter softcap magnitude by ', '天体物质软cap强度减少 ')
t('Thirty thousand degrees', '三万度')
t('Unlock Stars.', '解锁星辰。')
t('Obtain a Penteract.', '获得五维超立方。')
t('Reach ', '达成 ')
t(' Antimatter.', ' 反物质。')
t('Purchase ', '购入 ')
t(' Endgame Skills.', ' 终局技能。')
t('Obtain ', '获得 ')
t(' Free Tesseracts.', ' 免费超立方体。')
t('Purchase all the Break Eternity Upgrades.', '购入所有破永恒升级。')
t('Perform a Celestial Eternity.', '进行一次天体永恒。')
t('Hadronize Lai\'tela\'s Reality ', '对莱特拉真境进行强子化 ')
t(' times.', ' 次。')
t('Get ', '获得 ')
t(' total Ra Celestial Memory levels.', ' 拉天体记忆等级总计。')
t('Unlock all star types.', '解锁所有星辰类型。')
t('Reach ', '达成 ')
t(' Celestial Points of Eternity.', ' 永恒天体点。')

# === REWARDS (static strings) ===
t('Your Achievement multiplier to the 1st Antimatter Dimension is squared.', '你对第一反物质维度的成就倍率被平方。')
t('Multiply the 2nd Antimatter Dimension by the Antimatter Exponent.', '第二反物质维度倍率乘以反物质指数。')
t('The 5th and higher Antimatter Dimensions are doubled.', '第五及以上反物质维度倍率翻倍。')
t('Multiply all Antimatter Dimensions by Ninety Degrees.', '所有反物质维度倍率乘以九十度。')
t('Dimensional Sacrifice is stronger.', '维度献祭更强。')
t('Dimensions 1-7 are ', '维度一至七强度提升 ')
t(' stronger.', '。')
t('Multiply starting tick speed by ', '起始速度倍率提升至 ')
t('Start with ', '起始反物质 ')
t(' antimatter.', '。')
t('Unlock two new Infinity Upgrades- ', '解锁两个新无限升级—— ')
t(' IP multiplier and offline IP generation.', ' 无量点倍率与离线无量点产生。')
t('Each Antimatter Dimension gains a boost proportional to tier', '每个反物质维度获得与其等级成正比的增幅')
t('The ', '第 ')
t(' Antimatter Dimension is stronger in the first ', '反物质维度在前 ')
t(' minutes of Infinities.', ' 分钟的无限中强度提升。')
t('All Dimensions are ', '所有维度强度提升 ')
t(' stronger.', '。')
t('All Antimatter Dimensions are ', '所有反物质维度强度提升 ')
t(' stronger.', '。')
t('All Antimatter Dimensions are significantly stronger in the', '所有反物质维度在')
t(' first ', '前 ')
t(' seconds of Infinities.', ' 秒的无限中显著增强。')
t('Your Achievement bonus affects Infinity Dimensions.', '你的成就加成影响无限维度。')
t('Extremely small multiplier to Antimatter Dimensions based on time played.', '基于游玩时间给予反物质维度极小倍率。')
t('All Infinity Dimension multipliers are doubled.', '所有无限维度倍率翻倍。')
t('Gain ', '获得 ')
t(' more Eternities.', ' 更多永恒。')
t('Make the Infinity Point formula better.', '优化无量点公式。')
t('Start Eternities with ', '永恒起始时拥有 ')
t(' Infinity Points.', ' 无量点。')
t('Time Dimensions gain a multiplier based on tickspeed.', '时间维度基于tick速度获得倍率。')
t('You keep your Replicanti and ', '你保留复制元和 ')
t(' Replicanti Galaxy on Infinity.', ' 复制元星系于无限时。')
t('Replicanti Galaxies divide your Replicanti by ', '复制元星系将复制元除以 ')
t(' instead of resetting them to ', '而非重置为 ')
t('All Infinity Dimensions are stronger based on Infinity Points.', '所有无限维度基于无量点增强。')
t('Double Infinity Power gain.', '无限之力产出翻倍。')
t('Antimatter Dimensions gain a multiplier based on current antimatter.', '反物质维度基于当前反物质获得倍率。')
t('Antimatter Dimensions are stronger the more unspent antimatter you have.', '反物质维度越强，未花费反物质越多。')
t('Additional ', '额外 ')
t(' multiplier to Infinity Points.', ' 无量点倍率。')
t('All Galaxies are ', '所有星系强度提升 ')
t(' stronger.', '。')
t('Gain ', '获得 ')
t(' more Infinities.', ' 更多无限。')
t('Galaxies no longer reset Dimension Boosts.', '星系不再重置维度跃升。')
t('Unlock V, the Celestial of Achievements.', '解锁成就之天体——V。')
t('Gained Glyph level is increased by number of distinct Glyph types equipped.', '所得符文等级随已装备不同符文类型数增加。')
t('Unlock Teresa, the Celestial of Reality.', '解锁真境之天体——特蕾莎。')
t('+', '+')
t(' to Glyph rarity.', ' 至符文稀有度。')
t('Black Hole durations are ', '黑洞持续时间延长 ')
t(' longer.', '。')
t('Gain ', '获得 ')
t(' generated Time Theorems, and a free coupon to McDonalds™️.', ' 生成时间定理，以及麦当劳™️免费券一张。')
t('Black Hole power increased by ', '黑洞强度增加 ')
t('Are you sure these are the right way around?', '此方向无误乎？')
t('Make both Black Holes permanent.', '使两个黑洞永久化。')
t('Black Hole intervals are ', '黑洞间隔缩短 ')
t(' shorter.', '。')
t('Your Achievement bonus affects Infinity Dimensions.', '你的成就加成影响无限维度。')
t('Extremely small multiplier to Antimatter Dimensions based on time played.', '基于游玩时间给予反物质维度极小倍率。')
t('All Infinity Dimension multipliers are doubled.', '所有无限维度倍率翻倍。')
t('All Infinity Dimensions are stronger based on Infinity Points.', '所有无限维度基于无量点增强。')
t('Double Infinity Power gain.', '无限之力产出翻倍。')
t('Gain a multiplier to Tachyon Particle and Dilated Time gain based on Antimatter Galaxies.', '基于反物质星系获得超子微粒与延时间倍率。')
t('You start Eternities with all Infinity Challenges unlocked and completed.', '永恒起始时所有无限挑战已解锁且完成。')
t('You gain Replicanti ', '复制元产出速度提升 ')
t(' times faster.', ' 倍。')
t('All Infinity Dimensions are stronger based on Infinity Points.', '所有无限维度基于无量点增强。')
t('Gain a small multiplier to the Celestial Matter Conversion Exponent based on unnerfed Celestial Matter.', '基于未削弱天体物质获得天体物质转化指数的小倍率。')
t('Alpha Decay increases ', '阿尔法衰减增加 ')
t(' faster', ' 倍速')
t('Alpha Decay speed is boosted based on Dual Machines.', '阿尔法衰减速度基于双机器增强。')
t('Unlock Celestial Dimension Expansion.', '解锁天体维度扩展。')
t('Momentum increases ', '动量增加 ')
t(' faster.', ' 倍速。')
t('Unlock the automator.', '解锁自动化装置。')
t('Dimension Boosts are ', '维度跃升强度提升 ')
t(' stronger.', '。')
t('All Infinity Dimensions are stronger based on Infinity Points.', '所有无限维度基于无量点增强。')
t('Double Infinity Power gain.', '无限之力产出翻倍。')
t('Unlock Effarig\'s second shop.', '解锁埃法里格之第二商店。')
t('Unlock Divinity.', '解锁神性。')
t('Dilate Antimatter Dimension Multipliers based on purchased Endgame Skills, which is stronger in Pelle.', '基于已购终局技能给予反物质维度倍率延时间，在佩勒中更强。')
t('Gain a small power to Eternity Points based on Penteracts.', '基于五维超立方体给予永恒点小倍率。')
t('Raise the Antimatter Exponent to the power of ', '反物质指数以 ')
t(', but only inside Pelle.', ' 为指数，但仅在佩勒内有效。')
t('The time for Hadron effects to cap is halved.', '强子效应达到上限的时间减半。')
t('Get ', '获得 ')
t(' more memories.', ' 更多记忆。')
t('Reach ', '达成 ')
t(' Celestial Points of Eternity.', ' 永恒天体点。')
t('Time Theorems boost all forms of continuous non-dimension production', '时间定理提升所有连续非维度产出')

# Also handle the multiline string patterns
# "Gain ${formatInt(5)} more Eternities."
# These are handled in the T dictionary

# Apply all translations
for en, zh in T.items():
    if en in content:
        content = content.replace(en, zh)
        print(f"Translated: {en[:40]}... -> {zh[:40]}...")
    else:
        print(f"NOT FOUND: {en[:60]}...")

# Write back
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\nApplied translations to {filepath}")